concord-consortium/portal-report

js/components/image-question-details.js, js/components/multiple-choice-details.js, js/components/question-summary.js, js/components/question.js, js/core/report-data.js, js/core/transform-json-response.js, js/data/report.json
This was a simple task, so I grabbed it.  @pjanik  if you have time to review 
[#115460053]  (see similar PR in rigse / portal)
https://www.pivotaltracker.com/story/show/115460053
=> Change `children` to `responses` in report api format.

js/components/image-question-details.js, js/components/multiple-choice-details.js, js/components/question-for-class.js, js/components/question-for-student.js, js/components/question-summary.js, js/core/report-data.js, js/core/transform-json-response.js, js/data/report.json
This PR includes https://github.com/concord-consortium/portal-report/pull/2, so the #2 should be merged first (I did it, so the new code is updated too).
=> Change 'responses' to 'answers'

.travis.yml, README.md, package.json, test/components/question-summary_spec.js, test/test_helper.js
@pjanik  If you want to review.
This resolves #5, adds suport for mocha tests, building on Travis-CI
More tests will follow. This commit establishes a testing pattern.
=> Setup Mocha testing of  react components.

js/components/page.js, js/components/question-for-class.js, js/components/question-for-student.js, js/components/question.js, js/data/report.json
@pjanik  This is based on other PR, so only a17eafb needs review?
=> Change question numbering in reports.

js/actions/index.js
NB: The questions in the visibility_filter are now only set when the checkbox is changed.
=> Selection status for report filters saves when the checkbox is changed [#116249635]

js/actions/index.js, js/components/report.js, js/containers/app.js, js/core/transform-json-response.js, js/data/report.json, js/reducers/index.js
This allows the teacher to click on the student's name in the portal to see a report for just that student.
See corresponding change in concord-consortium/rigse 3c05946
[#115801667]
https://www.pivotaltracker.com/n/projects/736901/stories/115801667
@pjanik @dougmartin  if you have a chance to look.
=> The teacher's individual student report is showing in the new format.

css/button.less, css/image-question-details.less, css/question.less, css/report.less, js/components/activity.js, js/components/image-question-details.js, js/components/investigation.js, js/components/page.js, js/components/question-for-class.js, js/components/question.js, js/components/report.js, js/components/section.js, js/data/report.json, package.json
This PR Should be reviewed after #26 
This adds larger fields for the author and notes in image questions.  As per https://www.pivotaltracker.com/story/show/116559551
=> Slide carousel adjustments

js/components/activity-feedback-row.js, js/components/student-report-link.js, js/containers/activity-feedback-panel.js, js/util/student-report-url.js
Wait for #42 to land before review.
=> 155600871 open user activity report

css/rubric-box.less, css/rubric-summary.less, css/summary-indicator.less, js/components/rubric-box.js, js/components/rubric-summary.js, js/components/summary-indicator.js, js/containers/activity.js, js/util/colors.js
This commit creates a light box view of the rubric summary.
Feature: Lightbox rubric summary view. +fix colors & border.  …
Fix the colors and borders for feedback summary:
[#155404659]
https://www.pivotaltracker.com/story/show/155404659
Create a lightbox rubric feedback summary
[155404750]
https://www.pivotaltracker.com/story/show/155404750
=> 155404750 light box rubric summary

css/feedback-panel.less, css/question.less, js/components/activity-feedback-row.js, js/components/feedback-row.js
Also fixes:  Prompt being cut off in activity feedback lightbox.
Also fixes:  Recovers some vertical space by grouping input fields into grid.
Story:
[#156548713]
https://www.pivotaltracker.com/n/projects/736901/stories/156548713
Rubric panel wont display all columns in narrow view
=> Fix: CSS that was preventing horizontal scrolling.

js/actions/dashboard.js, js/components/dashboard/dashboard.js, js/components/dashboard/dropdown.js, js/components/dashboard/sort-by-dropdown.js, js/containers/dashboard/dashboard-app.js, js/reducers/dashboard-reducer.js, js/selectors/dashboard-selectors.js, test/reducers/dashboard-reducer_spec.js, test/selectors/dashboard-selectors_spec.js
Hi @pjanik! I put together the dropdown to sort students today - thanks for leaving clues as to how it should work in the code :) Everything went pretty smoothly, including testing, but I do have a few questions I'll leave below. 
It's also worth noting I opened this request off your `tests` branch to pull in some helpful logic from your tests. This will probably cause some conflicts down the line, but I'm willing to resolve them as they come up.
=> Sort students

.gitignore, .travis.yml, css/dashboard/answer.less, css/dashboard/open-response-answer.less, cypress.json, cypress/integration/dashboard.spec.js, cypress/integration/open-response.spec.js, cypress/plugins/index.js, cypress/support/index.js, cypress/utils.js, js/components/dashboard/activity-answers.js, js/components/dashboard/activity-name.js, js/components/dashboard/answer.js, js/components/dashboard/dashboard.js, js/components/dashboard/open-response-answer.js, js/components/dashboard/student-name.js, js/data/report.json, package-lock.json, package.json, test/components/dashboard/open-response-answer_spec.js
Hi @pjanik! This PR has two parts: the open response answer cell, and Cypress tests. I had a little bit of trouble getting it to run on Travis, though it's mostly working now. 
Let me know if you'd rather pass off some of the Cypress review.
=> Open Response Answer + Cypress Tests

js/components/dashboard/expand-students.js, js/components/dashboard/multiple-choice-answer.js, package-lock.json, package.json, test/components/dashboard/multiple-choice-answer_spec.js
[#158162480]
The previous code was assuming that a question without a correct answer will always return `isCorrect=null` properties for every choice. That's not true. Sometimes all the choices have `isCorrect=false` what also means that there's no correct answer. New code decides whether given question has the correct answer or not by looking at all the choices and checking if there's at least one with `isCorrect=true`.
@ekosmin, could you take a look please?
You can also be interested in tests, as this case is pretty similar to your button case. I have two separate components. Instead of using `render` or `mount`, I render shallowly both of them and check whether the top one is passing right properties to its children. Then I test child component separately. Not saying that's it's better …
=> Fix multiple choice answer logic and update tests to check that

css/dashboard/activity-answers.less, css/dashboard/answer.less, js/components/dashboard/activity-answers.js, js/components/dashboard/activity-questions.js, js/components/dashboard/answer.js, js/components/dashboard/dashboard.js, js/components/dashboard/multiple-choice-answer.js, js/selectors/report-tree.js, test/components/dashboard/multiple-choice-answer_spec.js, test/selectors/report-tree_spec.js
[#158441023]
This PR adds a new column with scored multiple choice questions summary. Trudi requested that. It will show up only if given activity has any scored multiple choice question.
=> Add scored multiple choice questions summary

js/components/report/rubric-box.js, public/sample-rubric.json, test/components/report/rubric-box_spec.js
[Noah/Dave]:  Simple change to respect rubric cells as "non-applicable" for a particular criterion.
PT User Story: https://www.pivotaltracker.com/story/show/160794683
=> 160794683 mark rubric cell na

css/report/data-fetch-error.less, js/actions/index.js, js/api-middleware.js, js/api.js, js/components/report/data-fetch-error.js, js/reducers/index.js
Also handle network errors that occur during fetches
[#128503731]
=> Handle case where error occurs while saving teacher feedback

js/actions/index.ts, js/api.ts, js/components/report/question-for-student.js, js/containers/dashboard/answer.js, js/containers/report/answers-table.js, js/core/transform-json-response.ts, js/data/answers.json, js/data/class-data.json, js/data/offering-data.json, js/selectors/dashboard-selectors.js, js/selectors/report-tree.js, test/components/dashboard/answer_spec.js, test/selectors/dashboard-selectors_spec.js, test/selectors/report-tree_spec.js
Depends on:
- https://github.com/concord-consortium/lara/pull/436
- https://github.com/concord-consortium/rigse/pull/665
This PR changes matching of answer based on emails to matching based on platformUserId. Also, we make use of some new data provided by Firebase JWT. Dummy data and specs are updated.
=> Report service data/ids refactoring

css/report/activity.less, css/report/feedback-button.less, js/api.ts, js/components/dashboard/dashboard.js, js/components/report/multiple-choice-details.js, js/components/report/question-details.js, js/components/report/question-for-class.js, js/components/report/report.js, js/containers/dashboard/question-details.js, js/containers/report/answers-table.js, js/containers/report/question.js, js/containers/report/report-app.js, js/reducers/index.js, js/selectors/activity-feedback-selectors.js, js/selectors/compare-view-data.js, js/selectors/dashboard-selectors.js, js/selectors/report-tree.js, js/selectors/report.js, js/util/misc.ts, js/util/student-report-url.js, test/components/dashboard/answers-table_spec.js, test/selectors/report-tree_spec.js
1. Fixes a bug that was showing up after multiple choice question has been deleted from an activity, but some answers were present.
2. Control buttons are fixed now (they work, but they don't save settings anywhere).
3. Feedback buttons are hidden now as this functionality is not ready yet.
4. Students sorting is fixed and made more consistent.
5. Multiple question summary is fixed.
6. Print dialog closing was causing a JS error sometimes. It might be an older bug, but it's fixed now.
=> Miscellaneous bug fixes

js/api.ts, js/components/report/activity-feedback-for-student.js, js/components/report/activity-feedback-row.js, js/containers/report/activity-feedback-panel.js, js/containers/report/activity.js, js/containers/report/answers-table.js, js/selectors/activity-feedback-selectors.js, test/components/dashboard/answers-table_spec.js
This PR fixes / updates more things related to Feedback (see commit names). I think that it should address all the missing tasks from this PT story:
https://www.pivotaltracker.com/story/show/166241028
=> Firestore feedback updates

.gitignore, js/components/report/activity-feedback-row.js, js/components/report/question-summary.js, js/containers/report/question-feedback-panel.js, js/selectors/activity-feedback-selectors.js, test/selectors/activity-feedback-selectors_spec.js
[#167871598]
This PR fixes statistics in the feedback panel and ensures that students with no response are listed there. Note that it isn't based on master, but on the rubric-related branch.
=> Fix feedback statistics, show which students haven't started activity

js/components/report/activity-feedback-row.js, js/components/report/student-report-link.js, js/containers/report/activity-feedback-panel.js, js/core/transform-json-response.ts, js/reducers/index.js, js/util/student-report-url.js
=> Add support of `activityIndex` URL param

js/components/report/feedback-row.js, js/containers/report/question-feedback-panel.js
It was crashing when teacher was trying to open feedback panel for interactive or labbook question type.
=> Fix feedback panel

js/components/report/interactive-iframe.js
=> Add prop to interactive iframe to allow fullscreen

js/api.ts, js/components/report/interactive-iframe.js, js/selectors/report-tree.js, test/api_spec.js, test/components/report/interactive-iframe_spec.js, test/selectors/report-tree_spec.js
Also fixed a runtime error (white page of death) when an activty has no questions.
=> Added getFirebaseJWT iframe-api endpoint [#171749310]

css/portal-dashboard/custom-select.less, css/portal-dashboard/variables.less, js/components/portal-dashboard/class-nav.tsx, js/components/portal-dashboard/custom-select.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, public/index.html
Draft PR that adds a custom dropdown select menu and uses it to set the student sorting.
=> 172806422 sort student list

cypress/integration/geode-dashboard-smoke-test.spec.js, cypress/integration/inline-iframe.spec.js, cypress/integration/portal-report-smoke-test.spec.js, js/actions/index.ts, js/api.ts, js/data/activity-answers.json, js/data/activity-structure.json, js/data/average-class-activity-answers.json, js/data/average-class-data.json, js/data/small-class-data.json, js/data/xtra-large-class-data.json
Added a class of 36 students with variety of names
Added an activity with variety of question types, interactive types, and correct and wrong answers
=> Add mock data

css/portal-dashboard/portal-dashboard-app.less, css/portal-dashboard/progress-legend.less
This PR includes a small tweak to set the font family at the main portal dashboard component so Lato is propagated to child components.
=> Update new portal dashboard to font family with lato

cypress/integration/portal-dashboard-smoke-test.spec.js, js/components/portal-dashboard/class-nav.tsx, js/components/portal-dashboard/custom-select.tsx, js/components/portal-dashboard/header.tsx, js/components/portal-dashboard/legend-container.tsx, js/components/portal-dashboard/level-viewer.tsx, js/components/portal-dashboard/student-list.tsx
This PR adds a handful of simple Cypress tests to the top level portal dashboard components.
=> Add component Cypress tests

css/portal-dashboard/class-nav.less, css/portal-dashboard/level-viewer.less, css/portal-dashboard/num-students.less, css/portal-dashboard/variables.less, cypress/integration/portal-dashboard-expand-activities.spec.js, js/actions/dashboard.js, js/components/portal-dashboard/level-viewer.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/reducers/dashboard-reducer.ts, js/selectors/dashboard-selectors.js, public/index.html, test/reducers/dashboard-reducer_spec.js
This adds expanding activity buttons, and `currentActivity` prop to the dashboard state that can be used by the question views.
=> Add activity buttons

css/portal-dashboard/level-viewer.less, css/portal-dashboard/progress-legend.less, css/portal-dashboard/student-answers.less, css/portal-dashboard/variables.less, cypress/integration/portal-dashboard-expand-activities.spec.js, js/components/portal-dashboard/level-viewer.tsx
This adds
* Score boxes to the right
* No pages if there are no questions
* Blue lines between pages and between activities
* Fixes the spacing of activity buttons when there are lots of them
This also tweaks the blue lines in the question columns to match, but if that conflicts with your work, @mklewandowski , let me know.
=> Fix question columns

js/components/portal-dashboard/header-menu.tsx
This small PR makes changes to eliminate console errors that appeared when running the app in hopes of keeping the console messages as clear as possible.
=> Fix console errors

css/portal-dashboard/all-responses-popup/popup-class-nav.less, css/portal-dashboard/all-responses-popup/spotlight-dialog.less, css/portal-dashboard/student-names.less, css/portal-dashboard/variables.less, cypress/integration/portal-dashboard-all-responses-popup.spec.js, js/components/portal-dashboard/all-responses-popup/popup-class-nav.tsx, js/components/portal-dashboard/all-responses-popup/popup-header.tsx, js/components/portal-dashboard/all-responses-popup/spotlight-dialog.tsx, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx
Adds the class nav area with the view list by toggle and the spotlight toggle
=> Add popup class nav

cypress/integration/portal-dashboard-anonymize.spec.js, cypress/integration/portal-dashboard-smoke-test.spec.js, cypress/integration/portal-dashboard-student-sort.spec.js, js/components/portal-dashboard/custom-select.tsx
Expand tests for anonymize student name toggle and student sort dropdown.
=> Add tests to anonymize and sort students

js/components/portal-dashboard/level-viewer.tsx
Update the score icon used in the level viewer with the new svg icon imported into the project as a file (rather than pulled from index.html).
=> Update score icon in level viewer with new svg

__mocks__/iframe-phone.ts, cypress/integration/inline-iframe.spec.js, js/components/report/iframe-answer.js, js/components/report/interactive-iframe.js, js/data/answers.json, test/components/report/interactive-iframe_spec.js
Support new "answerText" metadata and "height" iframe-phone message.
=> Support "answerText", listen to "height" iframe-phone message

css/portal-dashboard/level-viewer.less, css/portal-dashboard/progress-legend.less
Update legend colors to match UI spec.  This was a request from Michael as we are using a color for the legend borders which is designed to be used only in specific locations elsewhere in the design.
=> Update legend colors

css/portal-dashboard/answers/answer-modal.less, css/portal-dashboard/question-area.less, js/components/portal-dashboard/answers/answer-modal.tsx, js/components/portal-dashboard/question-area.tsx, js/data/sequence-structure.json
Adds the drawing prompt to the image question prompt question prompt to question area in both overlay and all student response view
=> 174712393 add drawing prompt

css/portal-dashboard/all-responses-popup/popup-student-response-list.less, css/portal-dashboard/student-names.less
This small PR fixes the following student name display issues (might need to switch classes to test):
- long names are not displayed properly in response table
- long names cause selection bubble to format incorrectly in all student response overlay
=> Fix layout issues in student name container

css/portal-dashboard/level-viewer.less, cypress/integration/portal-dashboard/portal-dashboard-expand-activities.spec.js, js/components/portal-dashboard/level-viewer.tsx
This PR adds minor improvements to the score that appears in the level viewer:
- prevent score from behaving as button.  Remove hover, active, and cursor states
- better positioning of score check
=> Improvements to the activity score

js/components/portal-dashboard/all-responses-popup/popup-class-nav.tsx, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx, js/components/portal-dashboard/anonymize-students.tsx, js/components/portal-dashboard/class-nav.tsx, js/components/portal-dashboard/toggle-control.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/selectors/dashboard-selectors.js
This PR syncs the anonymize toggle in the upper left nav and in the all student responses view so that they always display the same on/off state.
=> Sync anonymize toggles

css/portal-dashboard/student-answers.less, js/components/portal-dashboard/student-answers.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx
Fix the score displayed in the student response table.  Use multiple choice correct/incorrect to determine the score.
=> Fix student score calculation

css/portal-dashboard/student-answers.less, js/components/portal-dashboard/student-answers.tsx
When a user has all of the scored questions correct, highlight their score with a green box (this was previously part of the UI and removed when we reworked the score).
=> Add perfect score green container

css/portal-dashboard/level-viewer.less, js/components/portal-dashboard/level-viewer.tsx
This PR adds the five unique default activity colors to the activity buttons in the level viewer.
=> Add activity button colors

css/portal-dashboard/all-responses-popup/student-responses-popup.less, css/portal-dashboard/header.less, css/portal-dashboard/level-viewer.less, css/portal-dashboard/question-overlay.less, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx
This PR includes a series of small UI fixes to adhere to the spec:
- Improve the question overlay animation when the component is displayed (both the height and width should appear to grow)
- Update the cover height so we do not hide the legend border
- Make assignment text in header bold
- Fix the background color of the student response container so it lines up with the upper left nav inside of the all student responses view:
=> UI updates to adhere to spec

css/portal-dashboard/question-area.less, cypress/integration/portal-dashboard/portal-dashboard-all-responses-popup.spec.js, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx, js/components/portal-dashboard/question-area.tsx, js/components/portal-dashboard/question-navigator.tsx, js/components/portal-dashboard/question-overlay.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/core/transform-json-response.ts, js/data/offering-data.json, js/reducers/report-reducer.ts
Adds ability to open activity link from the question overlay and all student response popup question area.
Adds ability to open the activity in teacher edition mode if available. If teacher edition mode is not available, teacher edition icon is not shown.
=> 174830488 overlay activity link

css/portal-dashboard/all-responses-popup/student-responses-popup.less, js/containers/portal-dashboard/portal-dashboard-app.tsx
This PR adds a slide in animation to the `StudentResponsePopup` component.  Animations are done using `react-transition-group`.  Note that this is a more simplistic approach than what was used in the previously opened PR seen here:
https://github.com/concord-consortium/portal-report/pull/232
=> Animate student response popup

css/portal-dashboard/all-responses-popup/popup-header.less, cypress/integration/portal-dashboard/portal-dashboard-all-responses-popup.spec.js, js/components/portal-dashboard/all-responses-popup/popup-header.tsx
This add the ability to close the all response pop up when clicking on the Activity name on the top left.
=> 174800482 close popup

js/components/portal-dashboard/all-responses-popup/popup-student-response-list.tsx
This PR fixes the missing student name in the image answer modal dialog when launched from the all student responses window.
=> Fix student name in modal popup

css/portal-dashboard/all-responses-popup/popup-student-response-list.less, js/components/portal-dashboard/all-responses-popup/popup-student-response-list.tsx
This PR adds a highlight color to the student row in the All Student Responses view when the student row is selected for spotlight.
=> Highlight student row when student is checked for spotlight

css/portal-dashboard/all-responses-popup/popup-student-response-list.less, js/components/portal-dashboard/all-responses-popup/popup-student-response-list.tsx, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx
This PR prevents the user from spotlighting a student who has not provided an answer to the current question.
=> Disable spotlight for students with no answer

cypress/integration/portal-dashboard/portal-dashboard-all-responses-popup.spec.js, cypress/support/index.js, js/components/portal-dashboard/all-responses-popup/spotlight-student-list-dialog.tsx, package-lock.json, package.json, tsconfig.json
adds tests for the spotlight dialog feature
=> adds cypress-commands library

css/portal-dashboard/all-responses-popup/spotlight-student-list-dialog.less, css/portal-dashboard/variables.less, js/components/portal-dashboard/all-responses-popup/popup-student-response-list.tsx, js/components/portal-dashboard/all-responses-popup/spotlight-student-list-dialog.tsx, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx
This PR adds highlight colors to the spotlight student rows.  The highlight colors are changed by pressing the spotlight button next to the student name.
Note that I'm using an array of `SelectedStudent` objects in my React state inside the `StudentResponsePopup` component.  I think my state changes are safe, but there is some trickiness here when dealing with changing object properties inside of an array in state.  In my case I'm making a new `SelectedStudent` object that gets put into the array - so I think I'm safe.  But this is worth looking at.
=> Add dynamic spotlight colors

css/portal-dashboard/header.less, css/portal-dashboard/portal-dashboard-app.less
Improve the animation of level viewer contents by putting the level viewer behind other components.
=> Improve level viewer animation

css/portal-dashboard/all-responses-popup/spotlight-student-list-dialog.less, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx
Fades selected student dialog in and out
=> Spotlight animation

README.md, package-lock.json, package.json
Update readme and remove version number from package.json in anticipation of new build.
=> Internal updates to readme and package.json for 3.0.0 release

js/components/portal-dashboard/response-details/response-details.tsx
Fix the question count in the upper left nav view.
=> Fix question count in upper left nav

css/portal-dashboard/header.less, js/components/portal-dashboard/account-owner.tsx
PT story: https://www.pivotaltracker.com/story/show/176083674
[#176083674]
* move account icon to the left of teacher name
=> Header: Move teacher icon

css/portal-dashboard/progress-legend.less, css/portal-dashboard/student-answers.less, cypress/integration/portal-dashboard/portal-dashboard-smoke-test.spec.js, js/components/portal-dashboard/legend-container.tsx
PT story: https://www.pivotaltracker.com/story/show/176083706
[#176083706]
=> Change "Not yet started" to "Not started"

css/portal-dashboard/portal-dashboard-app.less, js/containers/portal-dashboard/portal-dashboard-app.tsx
Remove the animation from the response details view when it is shown to the user. 
Can be demoed here:
http://portal-report.concord.org/branch/response-animation/?portal-dashboard
=> Remove response details animation

css/portal-dashboard/student-names.less, cypress/integration/portal-dashboard/portal-dashboard-response-table.spec.js, js/components/portal-dashboard/question-navigator.tsx, js/components/portal-dashboard/question-overlay.tsx, js/components/portal-dashboard/response-details/popup-class-nav.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/components/portal-dashboard/student-names.tsx, js/components/portal-dashboard/student-navigator.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/util/misc.ts
Adds ability open the response view when user clicks on student name. Response View opens in question mode of the student clicked on
=> 176081835 student link

css/portal-dashboard/answer-compact.less, css/portal-dashboard/student-answers.less, img/svg-icons/feedback-answer-updated-badge-icon.svg, img/svg-icons/feedback-question-badge-icon.svg, js/components/portal-dashboard/student-answers.tsx, js/containers/portal-dashboard/answer-compact.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/util/answer-utils.ts
Adds feedback badges to progress view.
When user Turns on Hide Feedback Badges from header menu, the feedback badges are not shown.
If a teacher submits a feedback, a solid green badge appears on to the side of the answer icon in progress view.
If a student changes an answer, the badge goes from solid green to green with white circle.
=> 176083750 feedback badge progress view

css/portal-dashboard/feedback/feedback-rows.less, js/components/portal-dashboard/feedback/activity-feedback-textarea.tsx, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/feedback-question-rows.tsx, js/components/portal-dashboard/feedback/question-feedback-textarea.tsx, js/components/portal-dashboard/feedback/question-level-feedback-student-rows.tsx
PT Story: https://www.pivotaltracker.com/story/show/176083561
[#176083561]
* Adds a separate component for feedback textareas
* Adds selected  state to textareas
* Makes textarea height responsive to the amount of text entered
=> Feedback text entry fields

css/portal-dashboard/feedback/feedback-note-modal.less, css/portal-dashboard/feedback/feedback-note-toggle.less, cypress/integration/portal-dashboard/portal-dashboard-feedback.spec.js, js/components/portal-dashboard/feedback/feedback-note-modal.tsx, js/components/portal-dashboard/feedback/feedback-note-toggle.tsx
PT Story: https://www.pivotaltracker.com/story/show/176161785
[#176161785]
* Feedback note button has default, hover, and selected states
* When button is clicked, open popup dialog
* Popup has a button to close the popup that reads "Got it" with default, hover, and pressed states
=> Feedback note popup

css/portal-dashboard/feedback/feedback-rows.less, cypress/integration/portal-dashboard/portal-dashboard-feedback.spec.js, js/components/portal-dashboard/feedback/activity-feedback-textarea.tsx, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/feedback-question-rows.tsx, js/components/portal-dashboard/feedback/question-feedback-textarea.tsx, js/components/portal-dashboard/feedback/question-level-feedback-student-rows.tsx
PT Story: https://www.pivotaltracker.com/story/show/176162188
[#176162188]
=> Feedback Report: Feedback Badges

js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/containers/portal-dashboard/feedback/activity-feedback-panel.tsx, js/containers/portal-dashboard/feedback/question-feedback-panel.tsx
This PR sets the activity and question feedback settings when we display the activity and question feedback panels.  We must set the feedback type (text in both cases) before we can start providing feedback to the students.
=> 176162207 feedback settings

css/portal-dashboard/response-details/response-details.less, css/portal-dashboard/student-navigator.less, cypress/integration/portal-dashboard/portal-dashboard-feedback.spec.js, js/components/portal-dashboard/activity-navigator.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/components/portal-dashboard/student-navigator.tsx
PT Story: https://www.pivotaltracker.com/story/show/176620502
[#176620502]
These changes fix a couple small issues within the activity navigator section. They change the background color from orange to teal when working with activity-level feedback, and ensure the activity title and nav elements don't appear when working with a standalone activity (as opposed to an activity within a sequence).
=> Fix issues with activity navigator styling.

css/portal-dashboard/feedback/feedback-info.less, css/portal-dashboard/response-details/popup-class-nav.less
PT Story: https://www.pivotaltracker.com/story/show/176599717
[#176599717]
These changes add active state styling for some buttons that were missing it.
- view list by toggle buttons
- feedback level toggle buttons
=> Button Active State

css/portal-dashboard/feedback/feedback-info.less
Made some adjustments to positions becuase fo the font change
=> Added font family to activity/question toggle

css/portal-dashboard/response-details/popup-class-nav.less, img/svg-icons/refresh-icon.svg, js/containers/portal-dashboard/popup-class-nav.tsx
Part of the bigger feedback sorting story. This just adds the refresh sort button. It doesn't do anything yet.
=> Adds the refresh sort button to pop-class-nav

cypress/integration/portal-dashboard/portal-dashboard-feedback.spec.js, cypress/support/index.js, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/rubric-table.tsx, js/components/portal-dashboard/student-answers.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/reducers/feedback-reducer.ts, js/util/activity-feedback-helper.ts, package-lock.json, package.json
Feedback badge should now show activity feedback given when either text or rubric feedback is given, and address the bug of when one of the is deleted.
The activity feedback status is synced in both feedback view and progress view
=> 176812935 deleted feedback bug fix

css/portal-dashboard/class-nav.less, css/portal-dashboard/custom-select.less, css/portal-dashboard/portal-dashboard-app.less, css/portal-dashboard/student-names.less, cypress/integration/portal-dashboard/portal-dashboard-feedback.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-details.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-table.spec.js, cypress/integration/portal-dashboard/portal-dashboard-student-sort.spec.js, js/containers/portal-dashboard/portal-dashboard-app.tsx
Refactors the header to only show one header when in feedback and response detail view.
Updates cypress test to reflect the changes.
=> Changes the z-index of the different parts of the progress view.

js/actions/index.ts
PT Story: https://www.pivotaltracker.com/story/show/178787916
[#178787916]
=> Fix AP Report not loading for Sequences

js/components/report/interactive-iframe.js, test/components/report/interactive-iframe_spec.js
=> Parse interactive state JSON before sending it to the iframe interactive

.github/workflows/ci.yml, js/api.ts, js/components/report/iframe-answer.js, js/components/report/interactive-iframe.js, js/containers/report/iframe-standalone-app.js, js/index.js, js/util/get-attachments-manager-options.ts, package-lock.json, package.json, test/api_spec.js, test/components/report/interactive-iframe_spec.js, test/util/get-attachments-manager-options_spec.js, webpack.config.js
This PR depends on LARA PR: https://github.com/concord-consortium/lara/pull/748
However, I've already deployed a beta version of `interactive-api-host` to NPM, so we can see how it's used in practive by other projects.
=> Add Attachments API support

cypress/integration/api-error.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-details.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-table.spec.js, cypress/plugins/index.js, cypress/support/index.js, js/util/get-attachments-manager-options.ts, test/actions/index_spec.js, test/api_spec.js, test/util/get-attachments-manager-options_spec.js
https://www.pivotaltracker.com/n/projects/2441249/stories/179540761
I can't run reports for anonymous users locally (not sure why, it works for logged-in students though, I need to fix it), but I'm 99% sure it's gonna fix the issue.
The second commit is unrelated, I just ran the linter and noticed that it was complaining about quite a few errors.
=> Fix attachments manager options helper

cypress/integration/feedback.spec.js, cypress/integration/standalone-iframe.spec.js, cypress/integration/student-report.spec.js, js/actions/index.ts, js/api.ts, js/containers/report/iframe-standalone-app.js
[#179622498]
This PR adds support of `shared_with: "context"` property of answers. It's necessary for the new Interactive Sharing Plugin to work.
=> Support sharing with the class

js/actions/index.ts, js/api.ts, js/reducers/report-reducer.ts, js/selectors/report-tree.js
- Added check for sourceKey
- Updated answer map generation to fall back to runKey when platformUserId is missing
- Hid controls in anonymous view
=> Added support for anonymous LARA users [#179623345]

js/components/portal-dashboard/questions/iframe-question.tsx
Without the key property the Iframe content is not reliably updating when question selection changes.
[#180647562]
https://www.pivotaltracker.com/n/projects/2441249
=> Add a key property to `ReportItemIframe` for each question.

js/components/portal-dashboard/question-navigator.tsx, js/components/portal-dashboard/report-item-iframe.tsx, js/components/report/answer.js, js/components/report/iframe-answer-report-item-attachment-audio.tsx, package-lock.json, package.json, test/components/report/iframe-answer-report-item-attachment-audio_spec.js
PT Story: https://www.pivotaltracker.com/story/show/181573452
[#181573452]
These changes add the ReportItemIframe to reports so that audio responses can be played back by students when viewing their work. There is also a small change to the playback button text and some very very minor code format adjustments.
=> Playback audio answers in show all my work (student reports)

js/components/portal-dashboard/activity-navigator.tsx, js/components/portal-dashboard/feedback/feedback-question-rows.tsx, js/components/portal-dashboard/feedback/question-level-feedback-student-rows.tsx, js/components/portal-dashboard/level-viewer.tsx, js/components/portal-dashboard/questions/multiple-choice-question.tsx, js/components/portal-dashboard/response-details/popup-question-answer-list.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/components/portal-dashboard/student-answers.tsx, js/components/report/iframe-answer-report-item-attachment.tsx, js/components/report/iframe-answer.tsx, js/containers/portal-dashboard/answer-compact.tsx, js/containers/portal-dashboard/answer.tsx, js/containers/portal-dashboard/feedback/question-feedback-panel.tsx, js/containers/portal-dashboard/popup-class-nav.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/containers/report/question-feedback-panel.js, js/reducers/feedback-reducer.ts, js/reducers/report-reducer.ts, js/selectors/report-tree.js, js/util/misc.ts, js/util/record-factory.ts, package-lock.json, package.json, test/containers/portal-dashboard/answer-compact_spec.tsx
This was the second part of my dev day work (after not so successful attempt to remove ImmutableJS completely: https://github.com/concord-consortium/portal-report/tree/rm-immutablejs). 
I've updated ImmutableJS from v3 to v4 as their changelog claimed much better typing. This triggered quite a lot of errors that I've tried to fix. Also, I've fixed some places where types were specified incorrectly (eg Map instead of List) - in most cases after double-checking them in the runtime.
I've made sure that unit tests and Cypress tests work, and I ran the report locally with test data and tried to click through most of the UI. But still, I think it'd be good to do a quite careful general smoke test /QA after this gets merged to ensure that nothing is broken.
=> Update ImmutableJS v3 to v4, fix new type errors, handle breaking changes

cypress/integration/portal-dashboard/portal-dashboard-response-table.spec.js, js/components/report/iframe-answer.tsx
Without this style tag injected both the tall and wide html responses are displayed.
=> Added injected style tag to html report item answers [#183557683]

js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/rubric-table.tsx, js/components/portal-dashboard/feedback/rubric-utils.ts, js/components/portal-dashboard/response-details/response-details.tsx, js/components/portal-dashboard/student-answers.tsx, js/containers/portal-dashboard/feedback/activity-feedback-panel.tsx, js/reducers/feedback-reducer.ts
Added background color to selected rubric score box using colors derived from a spectrum of dark to light green.
Also added a Rubric type as it was typed to any in the code.
=> feat: Add fill color to rubric score box when selected [PT-187021195]

css/portal-dashboard/feedback/rubric-table.less
Updated rubric table border color to match latest Zeplin spec.
=> fix: Updated rubric table border color [PT-187021195]

css/portal-dashboard/feedback/feedback-settings-modal-button.less, css/portal-dashboard/feedback/feedback-settings-modal.less, js/api.ts, js/components/portal-dashboard/feedback/feedback-settings-modal-button.tsx, js/components/portal-dashboard/feedback/feedback-settings-modal.tsx
Adds the contents of the Activity Score Settings dialog.
NOTE: this does not save the settings, that will be in a follow on PR.
=> feat: Added Activity Score Settings [PT-187021230]

css/portal-dashboard/feedback/rubric-table.less
The new spec changes the headers to bold.
=> feat: Set rubric table headers to bold [PT-187130855]

cypress/integration/portal-dashboard/portal-dashboard-feedback.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-table.spec.js, cypress/integration/portal-dashboard/portal-dashboard-student-sort.spec.js, js/components/portal-dashboard/response-details/response-details.tsx
Changes the default from question to activity level in the feedback report.
=> feat: Make Activity-level the default for Feedback Report [PT-187132915]

js/components/portal-dashboard/response-details/response-details.tsx
This is a fix to a regression created in the previous commit.
=> fix: Question navigator showing in activity level feedback view [PT-187132915]

README.md, css/portal-dashboard/feedback/feedback-settings-modal.less, js/actions/index.ts, js/api.ts, js/components/portal-dashboard/feedback/feedback-legend.tsx, js/components/portal-dashboard/feedback/feedback-settings-modal-button.tsx, js/components/portal-dashboard/feedback/feedback-settings-modal.tsx, js/components/portal-dashboard/feedback/feedback-settings-toggle.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/containers/portal-dashboard/feedback/feedback-info.tsx, js/util/debug-flags.ts, js/util/scoring.ts
Saves the activity score settings in Firebase.
This also adds a disableRubric query parameter to use during development and testing.
=> feat: Save Activity Score Settings [PT-187021230]

js/components/portal-dashboard/feedback/feedback-legend.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/components/portal-dashboard/student-answers.tsx, js/containers/portal-dashboard/feedback/feedback-info.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/util/scoring.ts
When No score is enabled, does not display the score field in each student's row of the dashboard or the Avg Score in the Feedback Info panel at the top
=> feat: Implement No Score setting [PT-187021303]

js/components/portal-dashboard/feedback/feedback-settings-modal.tsx
Changed from "Score with rubric" to "Use score from rubric"
=> fix: Update setting modal rubric option

css/portal-dashboard/feedback/feedback-settings-toggle.less, js/components/portal-dashboard/feedback/feedback-legend.tsx, js/components/portal-dashboard/feedback/feedback-settings-toggle.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/containers/portal-dashboard/feedback/feedback-info.tsx, js/selectors/activity-feedback-selectors.js, js/util/scoring.ts
Displayed in Feedback Summary panel above the Rubric Summary Icon when either Manual Score or Score with Rubric is enabled as the scoring setting.  Shows calculated average score across the class out of total possible score.
=> feat: Display Avg Score in Feedback Info panel [PT-187021319]

css/portal-dashboard/feedback/activity-feedback-score.less, css/portal-dashboard/feedback/feedback-rows.less, js/components/portal-dashboard/feedback/activity-feedback-score.tsx, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/rubric-table.tsx, js/components/portal-dashboard/feedback/score-input.tsx
This displays the rubric score when the question has been fully scored.  This also only shows the rubric score value in the table if the score type is rubric.
Finally this adds back code that was lost in a merge to check for a max score value of 999.
=> feat: Flesh out score with rubric [PT-187021252]

js/components/portal-dashboard/feedback/feedback-settings-modal.tsx
Changed "entered" to "selected" in description.
=> feat: Updated feedback settings description for rubric [PT-187021230]

js/components/portal-dashboard/feedback/activity-feedback-score.tsx, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/feedback-legend.tsx, js/components/portal-dashboard/feedback/feedback-settings-modal.tsx, js/components/portal-dashboard/feedback/feedback-settings-toggle.tsx, js/components/portal-dashboard/feedback/rubric-summary-icon.tsx, js/components/portal-dashboard/feedback/show-student-answers.tsx, js/components/portal-dashboard/level-viewer.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/containers/portal-dashboard/feedback/feedback-info.tsx
New events logged:
. Open activity score settings modal
. Set activity score setting
. Show/hide student responses to activity within feedback report . Open/close rubric summary details modal
. Enter/change manual score
. Click score button in progress dashboard
=> feat: Log events for new actions [PT-187192076]

js/components/portal-dashboard/feedback/activity-feedback-score.tsx
Removed throttling in score updates.
=> fix: Slow score updates [PT-187182524]

js/components/portal-dashboard/feedback/rubric-table.tsx
This uses the existing react tooltip library to render the processed markup.
=> feat: Display processed markup for score hint [PT-187173896]

js/components/portal-dashboard/feedback/feedback-legend.tsx, js/components/portal-dashboard/feedback/rubric-summary-icon.tsx, js/components/portal-dashboard/feedback/rubric-summary-modal.tsx
- Set rubric summary icon cursor to pointer
- Only show scores in rubric summary table when score type is rubric
- Only add completed student rubrics to the rubric summary
=> fix: Fit n' Finish [PT-187186199]

cypress/integration/feedback.spec.js, js/components/portal-dashboard/feedback/activity-feedback-score.tsx, js/components/portal-dashboard/feedback/activity-feedback-textarea.tsx, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/rubric-table.tsx, js/components/portal-dashboard/student-answers.tsx, js/reducers/feedback-reducer.ts, js/selectors/activity-feedback-selectors.js, js/util/activity-feedback-helper.ts, js/util/scoring.ts
Changes:
1. Changed hasBeenReviewed flag from set when feedback is saved to set when feedback loaded from Firebase.
2. Updated feedback icons to also show when score is set and changed hasRubricFeedback to ignore 0 scores.
3. Changed getStudentFeedbacks() selector to not filter on hasBeenReviewed flag.
=> feat: Change when hasBeenReviewed flag is set [PT-187220438]

js/containers/glossary-audio/hooks/use-glossary-audio-params.ts, js/containers/glossary-audio/hooks/use-glossary-audio.ts
Previously it was using the student id, which was incorrect.
=> fix: Change glossary JWT target user id to use user id [PT-187885744]

js/components/portal-dashboard/feedback/rubric-summary-modal.tsx
This was missing in the initial development.
=> feat: Add icons to summary table [PT-188404151]

js/api.ts
[#188673526](https://www.pivotaltracker.com/story/show/188673526)
=> feat: timestamps for feedback (PT-188673526)

js/components/portal-dashboard/feedback/activity-feedback-textarea.tsx, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/question-feedback-textarea.tsx, js/components/portal-dashboard/feedback/question-level-feedback-student-rows.tsx
[#188673526](https://www.pivotaltracker.com/story/show/188673526)
=> feat: add title attribute for timestamp value (PT-188673526)
