js/core/report-data.js, js/reducers/index.js
small PR when you get a chance @pjanik 
This small fix obfuscates student names when first loaded if `anonymousReport` is true.  
[#115799893]
https://www.pivotaltracker.com/story/show/115799893
=> fix: Names are not still hidden when you re-open the report

js/calculations/index.js, js/components/answer.js, js/components/question-for-student.js, js/components/report.js, js/reducers/index.js
@pjanik   Please have a look, and let me know if I abused the reducer pattern.  
It seems there are some operations which we will almost always want to apply to our state, when computing display values for example. I had thought maybe to do something more like this:
```
export default function reducer(state = Map(), action) {
let report = report(state.get('report'), action)
report = setHasSelectedQuestions(report)
return Map({
data: data(state.get('data'), action),
report: report
})
}
```
But instead decided to follow the patterns closer to what was being done for `setVisibilityFilterActive` 
[#116249337]
https://www.pivotaltracker.com/story/show/116249337
=> If nothing is selected, the report should always show everything.

css/report.less, js/components/report.js
This problem was intermittant, and the result of images not being (consistently) loaded on
the student page shortly after the print button was pressed.
After taking a deep dive into using image onLoad callbacks &etc, I decided it was simpler to hide the student view (instead of not rendering), so the images would be pre-loaded for printing.  
There may be performance issues with this down the road if we have a lot of student data, but I am not very worried at the moment.
NB: There is an issue with firefox not firing the media query events after the print dialog is closed,
so that we remain on the students report page.  I put this in as an issue ( #12 )
[#115800099]
https://www.pivotaltracker.com/story/show/115800099
=> Fix: Print for student report not showing images of image questions.

js/core/transform-json-response.js
This was throwing `transform-json-response.js:86Uncaught (in promise) TypeError: Cannot convert undefined or null to object(…)`
```
// Keys are generated by normalizr above, so just copy them to the object hashes.
function copyAnswerKeysToObjects(answers) {
Object.keys(answers).forEach(key => {
answers[key].key = key
})
}
```
[#116249081]
https://www.pivotaltracker.com/story/show/116249081
=> The report should handle case where no students have yet started the activity

css/image-answer.less, js/components/image-answer.js, js/components/image-question-details.js
(I was changing some of my github credentials around and I created the previous PR with the wrong account).
The react-responsive-carousel did not like having text and images together so I added the note to the legend instead of next to the image.
=> Add note to image answer carousel [#116559551]

css/image-answer.less, js/components/image-answer-modal.js
Since the React modal component has no click handler for the image itself I had to mount a click handler on the window when the component mounts.
=> Add a clear way to close the enlarged image window [#116559811]

js/actions/index.js, js/components/report.js, js/containers/app.js, js/core/transform-json-response.js, js/data/report.json, js/reducers/index.js
Small change to support this story "Individual activity report from a sequence shows in the new format"
This is PR should probably wait for #22 -- which is waiting on the RIGSE PR of the same name.
See concord-consortium/rigse 761c6b3 for the portal side of *this* PR.
[#115801707]
https://www.pivotaltracker.com/story/show/115801707
=> Individual activity report from a sequence shows in the new format

css/button.less, css/question.less, css/report.less, js/components/activity.js, js/components/investigation.js, js/components/page.js, js/components/report.js, js/components/section.js, package.json
This PR changes sticky behavior to match the mockups.
Replace `react-sticky`  with the simpler `react-stickynode`
Style adjustments accordingly. 
[#115343939]
https://www.pivotaltracker.com/story/show/115343939
=> Redo sticky navigation header.

css/page.less, css/question.less, js/components/maybe-link.js, js/components/page.js, js/components/question-for-class.js, js/components/question-for-student.js, js/components/question.js, js/core/migrations.js, js/data/report.json
This PR adds a new `url` parameter to the 'Page' entities sent in report JSON.
This allows teachers to click on links in the report to open the activity in LARA.
Portal and LARA side of this work has already been merged.
[#112613409]
https://www.pivotaltracker.com/story/show/112613409
=> Add page links in report back to runtime.

js/components/iframe-answer.js, js/components/interactive-iframe.js, js/components/question-for-class.js, js/components/question-for-student.js, js/components/question-header.js, package.json
This PR adds support of `InteractiveState` answer type. When this kind of answer is found, an iframe will be initialized using iframe-phone `initInteractive` call. `ExternalLinkUrl` is still supported. Both answer types work in a very similar way - "View work" link is shown. When it's clicked, an iframe is displayed.
Example:
This PR is related to https://github.com/concord-consortium/rigse/pull/303.
=> Add support of InteractiveState answer type

js/components/feedback-row.js, js/components/iframe-answer.js, js/data/report.json
This fixes a problem with some recent work in portal-report.
The result of that work was that interactives that should show as embedded iframes in the report were not showing up at all.  Clicking a view work link would have no effect in this case.
The changes in this PR are:
- do not automatically show iframes when opening the feedback dialog. This is for performance reasons. If a there are 30 students in a class and they all have done an interactive that wants to be reported on as an embedded iframe, this would really slow down the page browser when the dialog is opened.  This change is just the removal of the `alwaysOpen` from the answer component in the feedback-row.
- fix issue with logic about showing the embedded iframe. The problem with the old logic is that it was looking at …
=> Fix labbook items

js/components/activity-feedback-row.js, js/core/activity-feedback-data.js, js/data/report.json
Trying to present a smaller PR this time ;)
These are related to this auto-scoring story:
https://www.pivotaltracker.com/story/show/151224400
It fixes a bug where a student's activity level `automatic score` were summing question scores that included questions that were no longer being scored.  (Teacher changed their mind but we save the students scores incase the teacher decides to re-enable scoring)
Now when computing automatic scores for the activity or calculating the `maxScore` we check `scoreEnabled` first.
Also a fix for 'NaN' in a score field for `parseInt('')`,  and a change in the default `report.json` to show auto scoring working for an activity.
=> Auto-scoring bug fixes

css/feedback-panel.less, css/rubric-box.less, js/actions/index.js, js/actions/load-rubric.js, js/api-middleware.js, js/components/activity-feedback-row.js, js/components/feedback-options.js, js/components/feedback-overview.js, js/components/rubric-box.js, js/containers/activity-feedback-panel.js, js/containers/feedback-panel.js, js/core/activity-feedback-data.js, js/data/report.json, js/reducers/index.js, js/reducers/rubric-reducer.js, js/store/configure-store.js, js/util/scoring-constants.js, js/util/student-report-url.js
The summary of this feature is that activity authors can create criteria for evaluating students work at  the activity level. The rubric is a matrix of grading categories and proficiency levels. 
There are several rubric related stories tagged with `feedback` and PT.  This PR handles these two stories:
https://www.pivotaltracker.com/story/show/155404185 
https://www.pivotaltracker.com/story/show/155404153
> A teacher can select "use rubric" as one of the activity level feedback options, and they will see the rubric for this activity appear in activity-level feedback.
> An author can define a rubric using JSON. This structure of the rubric would be any number of grading categories, which could be scored using any number of proficiency levels. There could be a numerical value associated …
=> Beginning to add Rubric features.

js/actions/index.js, js/components/activity-feedback-row.js, js/components/rubric-box.js, js/core/transform-json-response.js, js/data/report.json, public/sample-rubric.json
For this PT Story:
"A teacher can select levels of proficiency in rubric-based feedback for each criteria and that score will be saved for that student."
https://www.pivotaltracker.com/story/show/155408322
This PR modifies actions that send activity-level feedback to portal report API, to include the students rubric feedback. Changes are in actions/index.js `enableActivityFeedback` and `updateActivityFeedback`
Corresponding view changes, and updates to the sample data. `report.json` and a new file `public/sample-rubric.json`
=> RubricFeedback for students #155408322

css/activity-feedback-for-student.less, css/feedback-panel-for-student.less, js/actions/index.js, js/actions/rubric.js, js/components/activity-feedback-for-student.js, js/components/feedback-panel-for-student.js, js/components/question-for-student.js, js/containers/activity-feedback-panel.js, js/containers/activity.js, js/containers/feedback.js, js/core/activity-feedback-data.js, js/data/report.json, js/reducers/activity-feedback-reducer.js
This pull request improves the student views (and the teacher's print view) in two key ways:
1. It adds feedback from the rubric to the activity level view.
2. It unifies all feedback areas with a consistent look. It also aligns feedback scores so they always appear on the right hand side, allowing teachers and students to easily check scores.
This PR is mainly component / container changes.  I also changed the dummy report JSON in minor ways to excise the new views.
PT: Story
[#153265633]
The student can see activity level feedback at the top of the report on their work.
When teacher does not have a text feedback, the score appears on the left side. When there is a text feedback, the scores are on the right side.
It would be easier to glance down one side to see scores if they were all …
=> Improvements to student feedback

css/activity.less, css/feedback-panel.less, css/report.less, js/components/activity-feedback-row.js, js/components/feedback-row.js, js/containers/activity-feedback-panel.js, js/containers/activity.js, js/containers/feedback-panel.js, js/data/report.json, js/util/misc.js
This PR addresses edge cases where question prompts are long and renders into a layout where its hard to provide feedback, because the scroll containers can't acquire enough screen real estate.
See screen shots and description in the PT story for examples of these cases.
Most of the changes are in stylesheets and some markup.
Specifically this PR:
* Truncates prompts to 200 characters, appending … to indicate its been shortened.
* Stylesheet changes to help maximize feedback area.
* Ensure that we can always scroll the feedback area.
* Line up UI elements in the right hand column.
* Use 70% of horizontal space for feedback.
* Modify `report.json` dummy data to include long prompts, and section names.
PT Story:
Long prompts make the feedback box unusable.
May be able to scroll, but can't …
=> Style and and layout changes to handle large question prompts.

js/components/feedback-panel-for-student.js, js/components/rubric-box.js, js/containers/rubric-test.js, js/rubric-test.js, public/rubric-test.html, webpack.config.js
This PR creates a new html page called `rubric-test.html` which can be used by authors to try out rubric JSON.  This is a **quick and dirty hack** to use until a graphical tool can be built.
The original story was to use an URL input field, but it was understood that a text area for writing complete JSON would also be acceptable.
PT Story:
An author writing a rubric can go to a URL to preview the rubric if they provide a parameter that is the URL to the rubric data.
[#155798025]
https://www.pivotaltracker.com/story/show/155798025
=> 155798025 preview rubric layout

js/containers/activity-feedback-panel.js, js/containers/feedback-panel.js
Wait for #44 
This stopped working a while back. The `refs` API had changed and I implemented the new method incorrectly.
Here is a longer discussion:
https://reactjs.org/docs/refs-and-the-dom.html#the-ref-callback-attribute
=> Fix:  Scroll Student into view.

css/rubric-box.less, js/components/rubric-box.js, public/sample-rubric.json
Story:
[#156316554]
Add referenceURL to Rubric JSON specification
This URL will be used to generate links in the teacher report that open a new tab containing a page that explains the rubric in detail.
If the field is blank, there is no link.
https://www.pivotaltracker.com/story/show/156316554
=> Feature: Link to referenceURL if specified in JSON

css/question.less, css/rubric-box.less, css/summary-indicator.less, js/components/rubric-box.js, js/components/summary-indicator.js, js/containers/activity.js, js/containers/feedback-panel.js, js/containers/rubric-test.js, package.json, public/sample-rubric.json, yarn.lock
This adds summary indicators to the activity feedback section.
Also adds a summary indicator to the rubric-test page.
PT Story:
[#155404659]
Add summary feedback indicators to the summary portal reports.
For numerical feedback, post the mean.
For rubric feedback, generate an icon that uses proportional color bars to represent what percentage of students scored at a particular level for each category.
https://www.pivotaltracker.com/story/show/155404659
=> 1: Feature: Add summary indicators to activity section.

js/components/activity-feedback-options.js, js/components/feedback-options-view.js, js/components/feedback-panel-for-student.js, js/components/numeric-text-field.js, js/containers/activity-feedback-panel.js, js/containers/activity.js, js/reducers/index.js, js/selectors/activity-feedback-selectors.js
Questions were showing options for 'use rubric for scoring' and other things which weren't possible.
This bug was a result of a partially completed factor-out of a common `feedbackOptionsView.` component.
This PR finishes the refactoring.
NOTE: Should be reviewed after #51
This PR if for this [PT story](https://www.pivotaltracker.com/story/show/157206977)
=> 157206977 Hide activity level feedback options for question level feedback.

js/components/feedback-panel-for-student.js, js/containers/activity.js
To be reviewed after #49 
Rubric summary should not be displayed when there is no rubric being used.  These summary items were also being displayed on the student reports.  This PR fixes both of these problems.
=> 155404659 don't display 'Rubric summary' when its innapropriate

css/feedback-filters.less
Because of a positioning stylesheet regression, the 'getting started' box could not be dismissed.
Story:
[#157362447]
https://www.pivotaltracker.com/story/show/157362447
=> Fix:  Overlay panel for 'getting started' could not be dismissed.

css/rubric-box.less, js/components/rubric-box.js, js/reducers/rubric-reducer.js
1. Rubric Box: pretty simple visual tweak - when there's data for only one student, use check mark instead of 100% and 0%. It's useful in Portal view where we display this icon and box for every student separately.
2. Rubric reducers - it seems to me that `RECEIVE_DATA` was totally broken. It didn't work for sequences (as they're not supported), it didn't do anything for activities (as it was going through activity children=sections that had no rubric information). In case of Activity, everything was set in LOAD_RUBRIC action anyway. I'm actually adding support of sequences, so I had to fix it, so the map is correct and error isn't thrown in another place. BTW, @knowuh, what's the purpose of this RECEIVE_DATA handler? Do we need it at all? I feel that we don't, as it was broken before and …
=> Fix Rubric reducers and tweak Rubric Box

.travis.yml, README.md, js/components/rubric-summary.js, js/library.js, package-lock.json, package.json, webpack.config.js
Portal Pages needs to use some Rubric-related components.
I've added a way to define separate library entry point that can be easily extended in the future.
I think README should describe how this is supposed to work and be deployed. Let me know if it's not clear.
Portal Report itself will provide two ways to use this lib - NPM and just an old-school script tag.
The question is which one we want to use in Portal Pages. 
I guess script tag could be slightly more automated, e.g. Portal itself could use Portal Report URL to generate library URL and then include it before Portal Pages. So, each time we would update Portal Report, we would update library too. But it seems a bit messy, we're depending on global variables, and so on.
I'd prefer NPM package defined in Portal Pages. It's a bit …
=> Export some React components as a separate library

css/dashboard/generic-answer.less, css/dashboard/helpers.less, css/dashboard/short-answer.less, js/components/dashboard/activity-answers.js, js/components/dashboard/generic-answer.js, js/components/dashboard/short-answer.js
A very simple component that shows an icon when there's any answer. This is the default cell now, but I renamed the existing `AnswerCell` to `ShortAnswer`, since it should be a useful basis for that in the future.
http://portal-report.concord.org/branch/generic-icons/index.html?dashboard=true
=> Replacing dummy answer cell with a generic answer icon

.travis.yml, js/api.js, package-lock.json, package.json, test/api_spec.js
[#158501911]
@scytacki, I've implemented it here, as that's what you seemed to prefer.
Note that we'll need to change Portal soon anyway to support highlighted questions, so we could consider adding `reportUrl` to external reports too. I think we don't do it only for "historical" reasons. It won't have any performance consequences until report actually uses this URL (that it can generate anyway, as that's what we do here). 
Also, when I add `http://localhost:8080/?dashboard=true` as an external report, the final URL is `http://localhost:8080/?dashboard=true?offering=...`. There are two question marks. I think you pointed out this issue recently. That's another reason to modify this Portal code. However, it does not break anything, the browser seems to handle it correctly anyway.
Anyway, …
=> Use offering URL as fallback when reportUrl is not available

js/actions/index.js, js/calculations/index.js, js/components/app.js, js/components/dashboard/activity-answers.js, js/components/dashboard/activity-questions.js, js/components/dashboard/dashboard.js, js/components/report/report.js, js/config.js, js/containers/report/report-app.js, js/core/transform-json-response.js, js/data/report.json, js/reducers/index.js, js/selectors/dashboard-selectors.js, js/selectors/report-tree.js, test/components/dashboard/activity-questions_spec.js, test/components/dashboard/dashboard_spec.js, test/selectors/report-tree_spec.js
This PR adds support of the featured questions. 
There's some small refactoring of how question visibility is calculated. I moved that to the tree selector, and I had to add the notion of questions which are "hiddenByUser" since the visibility is now more complex (depends on a few properties now - "isFeatured" and "hiddenByUser").
I hope the other bits should be clear. There's bunch of tests too. @ekosmin, there's example of testing selectors without providing the whole state. We can use `resultFunc` to test function directly and pass it some mock input.
=> Featured questions

css/report/rubric-box.less, js/components/report/rubric-box-for-student.js, js/components/report/rubric-box.js, package-lock.json, package.json, public/sample-rubric.json, test/util/rubric-helper_spec.js
[NP/DL]: "Rubric content can use simple markdown formatting."
* Added a React library, `markdown-to-jsx`. Used to convert descriptions in the rubric definition into styled HTML. Uses the markdown syntax.
* Updated the sample rubric with example markdown -- demonstrating text styes (bold, italic) and bullet items following new-line (\n) characters.
PT User Story: https://www.pivotaltracker.com/story/show/160794757
=> Added minimal markdown to JSX transform for selected rubric descriptions

js/components/report/rubric-box.js, test/components/report/rubric-box_spec.js
Add a simple Mocha test to verify rubric definitions can include Markdown, which will be rendered using the correct HTML tags in the report.
PT Story:
[#161133513]
https://www.pivotaltracker.com/story/show/161133513
=> Add mocha test for rubric Markdown Support.

js/components/report/feedback-options-view.js, js/components/report/numeric-text-field.js, test/components/report/numeric-text-field_spec.js
+ add test for NumericTextField
Part of  this PT Story:
'Make default max score 10 instead of 0.'
[#130389079]
https://www.pivotaltracker.com/story/show/130389079
=> Fix negative value bug in maxScore.

css/report/rubric-box-for-student.less, public/sample-rubric.json
[NP/DL] This PR addresses two PT stories:
* [Adding line break in rubric markdown is not consistent.](https://www.pivotaltracker.com/story/show/164439344)
* And, [Bulleted lists not indented (hanging outside of table cell) in rubric feedback markdown.](https://www.pivotaltracker.com/story/show/164439314)
In addition, while working on these problems, some tech debt was identified and capture in this PT story: [Reconcile two execution paths in portal-reports rubric code (tech-debt reduction)](https://www.pivotaltracker.com/story/show/164577719)
=> 164439344 markdown issues

js/components/report/rubric-box-for-student.js
Dan showed a video where the hyphen preceeding freedback is interpreted as
part of markdown.  This code change fixes this by placing the intro
hpyhen outside the markdown block.
[#164439344]
https://www.pivotaltracker.com/story/show/164439344
@DALove1025  -- Please have a look.
=> Fix:  Feedback hyphen causes bullet Markdown

js/containers/report/answers-table.js, test/components/dashboard/answer-table_spec.js
The app was crashing when the question detail box is being closed while showing student work.
It seems the question prop becomes null somewhere in the viewheirarchy when the close button is pressed.
A simple null check on in the  answer-table rendering stops the bug.
I added tests for the container that fail without the null check.
[#164583438]
https://www.pivotaltracker.com/story/show/164583438
=> Fixes crashing when displaying answer-table without selected question.

css/authoring/s3-upload.less, js/components/authoring/rubric-form.js, js/components/authoring/rubric-test.js, js/components/authoring/s3-upload.js, js/rubric-test.js, js/util/s3-helpers.js, package-lock.json, package.json, test/util/s3-helpers_spec.js, webpack.config.js
[#165795459]
Note that this PR is against `editing-form` branch. 
It adds a new tab to Rubric authoring with a simple form that lets you save or load rubric from S3 bucket. I've followed the same patterns that we used in Glossary authoring. Some inputs are stored in local storage or can be provided via URL. If we have enough data to generate rubric URL using URL params, it will be loaded on the page load.
I tried to make this component independent from glossary or rubric, and pretty standalone, so it can be reused in the future if needed. That's why there's `resource` word everywhere there.
I had to make two pretty significant changes in your form @knowuh.
I had to add `forceRenderTabPanel`, so tab views don't get constantly mounted and unmounted, each time we change a tab. It doesn't …
=> Add S3 upload to rubric authoring

js/components/authoring/rubric-form.js, js/components/authoring/rubric-test.js, js/core/rubric-migrations.js, public/sample-rubric.json, test/core/rubric-migration_spec.js
While fixing [#165857915]  "An author can not uncheck non-applicable rating"
https://www.pivotaltracker.com/n/projects/736901/stories/165857915
This migration generates an verbose representation of the `nonApplicableRatings` key of the `criteria` objects. The value is an array of strings which should match the ratings keys. In the past this was a sparse array of key names. Now it is redundantly including a string for every rating, using the rating id as a value if the rating should be skipped.
This is a confusing format, and only temporary while Kiley gets her work done.
I am working on the next migration, but it will not be backwards compatible, and will use the rating ids as boolean properties of the `nonApplicableRatings` values.  It will be in its own branch and PR because I don't …
=> Add rubric migrations and test for migrations.

css/report/report.less, js/components/report/report.js, js/containers/report/report-app.js
[#164604410]
This PR moves location of the refresh button.
Old header:
New header:
=> Move refresh button to the sticky header

js/actions/index.ts
@scytacki, what do you think about this fix?
Firestore doesn't let us query using substrings or regex.
I couldn't replace all HTTP with HTTPS not to break local dev env which is usually using HTTP. Also, if we think about it, this problem is specific to LARA only and its history. Other systems could use HTTP or HTTPS, and perhaps we shouldn't do assumptions about it.
Another solution would be to try a different protocol if the first one fails.
=> Always assume HTTPS protocol for CC activity URLs while querying Firestore

js/actions/index.ts, js/api-middleware.js, js/api.ts, js/data/report-settings.json, js/reducers/index.js
We save the teachers settings for the offering at this FireStore path:
/sources/${sourceId}/user_settings/${platformUserId}/offering/${contextId}
We dispatch all user settings updates to FireStore via the middleware API.
The RECEIVE_USER_SETTINGS action is the one which changes the active store.
Even when the network is disabled (wifi disconnected) the FireStore API dispatch method
works, and the RECEIVE_USER_SETTINGS is reliably called with valid parameters.
The FireStore rules are setup to allow unfettered access to:
`/sources/fake.portal/user_settings/1/offering/class123`
This allows us to test the report settings with fake portal data, without a valid JWT.
https://www.pivotaltracker.com/story/show/166240880
=> [#166240880] FireStore: Save assignment level report settings

js/api.ts
1. Technically it's OK to have trailing slashes in field values.
2. The platform is the authority on `platform_id` and it should be trusted here.
Full discussion can be found in the
[PT story](https://www.pivotaltracker.com/story/show/166241318)
[#166241318]
=> Do not modify the `platform_id` here in the report view code.

js/actions/index.ts, js/actions/rubric.js, js/api.ts, js/components/report/activity-feedback-options.js, js/components/report/activity-feedback-row.js, js/containers/report/activity-feedback-panel.js, js/selectors/activity-feedback-selectors.js
We have to do that, so the progress table in Portal keeps working.
Note that Portal progress table displays only activity-level feedback, so this data is being sent there.
This PR is relying on new Portal API:
https://github.com/concord-consortium/rigse/pull/681
=> Save feedback data to Portal

js/components/report/activity-feedback-row.js, js/containers/report/activity.js
[#168148207]
This is related to https://github.com/concord-consortium/rigse/pull/683
and this other PR describes details of the problem better.
Send only updated value. Some fields delay their update, so sending everything all the time could cause unexpected results.
=> Simplify activity feedback updates, send only changed value

js/actions/index.ts, js/api.ts, js/db.ts
This PR changes how an App initializes its firebase connection.
The new method looks for a `firebase-app` in the url parameters.  If it doesn't find one, it uses `report-service-dev` by default.
Because DB initialization happens later as a result. The `db` was modified, so that it wouldn't immediately initialize FireStore when loading. 
PT Story "Report should be configurable to run on Production"
[#168486280]
https://www.pivotaltracker.com/story/show/168486280
=> Use url parameters to chose FireStore DB source.

js/actions/index.ts, js/api.ts, js/reducers/index.js
This PR addes a new optional tool-id parameter. This parameter makes it possible for developers to configure the external report in their local portal so it uses a unique tool-id. By default the tool-id is taken from the resource url that is being reported on. Which for local development is typically `http://app.lara.docker`.  Since most developers use that same lara domain name it means by default all developers share the same data in firestore.
This PR also renames sourceId to sourceKey. The sourceKey is derived from the toolId, so by using a unique toolId the developer also gets a unique sourceKey.
=> Add tool id param

.travis.yml, cypress/integration/compare-project.spec.js, cypress/integration/feedback.spec.js, cypress/integration/geode-dashboard-smoke-test.spec.js, cypress/integration/portal-report-smoke-test.spec.js, cypress/integration/student-report.spec.js, cypress/support/elements/portal-report/header.js, cypress/support/sequence-helper.js, cypress/utils.js, js/api.ts, js/data/offering-data.json, js/reducers/index.js
This PR:
- refactors some of the cypress tests to remove redundant code
- fixes an issue with the travis config that was preventing it from sending the code coverage to code climate.
- disables firestore networking when the demo report is loaded
- fixes some cypress tests that were previously skipped because they were failing
- updates some cypress tests now that the user settings are starting empty on each test run
The most invasive change is the disabling of the firestore networking. This should only affect the demo report: the report that loads when you aren't coming from the portal.  Now the demo report won't remember any changes you made, but within the current tab session it should work as normal.
=> Improve automated tests

cypress/integration/feedback.spec.js, js/actions/index.ts, js/api-middleware.js, js/api.ts, js/db.ts, js/index.js, js/util/misc.ts, package-lock.json, package.json, public/index.html
- upgrades firebase to version 7.4.0 which includes the clearPersistence method
- adds two new url param flags to the report: enableFirestorePersistence and clearFirestorePersistence
- in order to support clearing the firestore persistence most calls to firebase.firestore() needed to be moved into promises so they could be delayed and not called until the clearing of the database was complete.  This was done by adding a 'global' promise called firestoreInitialized. Then having code that waits for this promise to resolve.
- disabling firestore Networking needed to moved earlier because in the student view some firestore requests were happening before the networking was disabled
- refactored actions/index.ts to remove redundant code which also reduced un tested code since the same function …
=> automated student feedback test

.travis.yml, cypress.json, cypress/integration/feedback.spec.js, js/components/common/button.js, js/components/report/activity-feedback-options.js, js/components/report/feedback-options-view.js, js/components/report/numeric-text-field.js, js/components/report/score-box.js, js/containers/report/activity-feedback-panel.js, js/containers/report/question-feedback-panel.js, js/store/configure-store.js, public/index.html, test/components/report/numeric-text-field_spec.js
The automatic total scoring which adds up the manual scores for individual questions was not reporting the correct value to the teacher. 
The cause of this problem was that the code was assuming a change of the value property on the NumericInputComponent would change the display. This component was mixing the patterns of controlled and uncontrolled components.  To fix the problem I made the NumericInputComponent be a explicitly uncontrolled. The parent components that use NumericInputComponent now have to deal with this uncontrolled approach. In some cases this is good because it makes the score behave the same as the text feedback box which is also uncontrolled. 
Bugs found while working on this:
- the wrong maxScore is saved and sent to the server when the teacher switches from manual …
=> fix feedback autoscore

cypress/integration/student-report.spec.js, js/actions/index.ts, js/api.ts, test/actions/index_spec.js
Earlier I had refactored this code to reduce redundant logic when creating the collection queries. But I missed the fact the the answer documents and the feedback documents use different keys for the platform info. So this PR introduces extra logic to use the right keys.
I think the redundant refactoring is still worth it since it makes this inconsistency more visible Hopefully we can unify these keys in the future and remove the extra key logic.
=> use appropriate keys for feedback documents vs answer documents

js/containers/dashboard/dashboard-app.js, test/selectors/report-tree_spec.js
A better fix for 🐞 Activity order scrambled in teacher dashboard
[#170757052]
The previous PR sorted the activities (from activityTree) by the position attributes.
That sorting is not required if we use the `getSequenceTree()` Selector which is careful to
map deep references to children by `id` from the shallow normalized representation of the children array.
`report-tree_spec.js` was modified to use keys instead of numeric indexes.
The activity map in the spec was modified so that the keys were out of sort order.
[#170757052]
https://www.pivotaltracker.com/story/show/170757052
=> Better 🐞 fix  for Activity scrambled in dashboard

package.json, s3_deploy.sh
This can be seen at https://portal-report.concord.org/branch/strip-pt-id/
Also bump Cypress test to 20s in an attempt to get flakey feedback test to work. (Doesn't seem to have made a significant difference.)
=> Strip Pivotal Tracker ID from branch names

README.md, css/report/iframe-standalone-app.less, cypress/integration/inline-iframe.spec.js, cypress/integration/standalone-iframe.spec.js, cypress/support/elements/portal-report/report-body.js, js/components/report/data-fetch-error.js, js/components/report/iframe-answer.js, js/components/report/interactive-iframe.js, js/components/report/question-for-class.js, js/containers/app.tsx, js/containers/report/iframe-standalone-app.js, js/reducers/index.js
This creates a stand-alone iframe container, to view full-size versions of student models, which can be viewed by including the url query parameters `iframeQuestionId` and `studentId`.
E.g. http://portal-report.concord.org/branch/172324236-standalone-iframe/?iframeQuestionId=mw_interactive_19&studentId=1
This also adds links for opening the stand-alone view to the main report, alongside the iframe toggles.
Currently, this just adds the link to all answers that have the property `displayInIframe`, i.e. those that should show embedded. Eventually we may want to have additional authorable properties defined in LARA which determine how the models should be displayed.
=> Standalone iframe

css/portal-dashboard/custom-select.less
This PR fixes a small click issue that was introduced in the custom select component.  To achieve the spec's requested fade in/fade out animation, the list of items is kept in the DOM and the opacity is changed depending on if it is shown or hidden.  However, the items could still be clicked even when they were hidden.  Changes in this PR disable pointer events and show the normal cursor when the list of items is hidden.
=> Fix errant clicks on list items

css/portal-dashboard/anonymize-students.less, css/portal-dashboard/class-nav.less, css/portal-dashboard/feedback.less, css/portal-dashboard/num-students.less, css/portal-dashboard/toggle-control.less, cypress/integration/portal-dashboard-smoke-test.spec.js, js/components/portal-dashboard/anonymize-students.tsx, js/components/portal-dashboard/class-nav.tsx, js/components/portal-dashboard/feedback.tsx, js/components/portal-dashboard/num-students-container.tsx, js/components/portal-dashboard/student-list.tsx, js/components/portal-dashboard/student-row.tsx, js/components/portal-dashboard/toggle-control.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx
This PR adds a generic toggle control that is used to anonymize student names and  turn on/off feedback.  At present, anonymizing student names is complete and the feedback control is in place but the underlying functionality is not yet in place.  Changes includes:
- add toggle control
- add anonymize student control
- add feedback control (functionality not yet in place)
- restructure controls in class nav to match UI spec
=> Add anonymize students control, and feedback skeleton control

css/portal-dashboard/class-nav.less, css/portal-dashboard/custom-select.less, cypress/integration/portal-dashboard-smoke-test.spec.js, js/components/portal-dashboard/class-nav.tsx, public/index.html
This PR adds in a UI stub for the class selection dropdown in the upper left navigation area.  A custom dropdown control is added that, at present, contains only the current, default class.  Eventually we will need to add other additional classes to the dropdown and change classes when a list item is selected.  However, this PR at least puts the basic UI in place.
=> Add stub for class selection control

css/portal-dashboard/level-viewer.less, js/components/portal-dashboard/level-viewer.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx
Add activity student progress bar to the level viewer beneath each activity.  Progress bar displays progress in terms of both started and completed activities.
=> Add activity progress bar in level viewer

css/report/bootstrap-components.less, js/components/dashboard/help-modal.js, js/components/report/image-answer-modal.js, js/containers/dashboard/question-details.js, js/containers/report/report-app.js
In mid-May we upgraded `react-bootstrap` from version 0.32 to version 1.0 which had the side-effect of breaking all of the modal dialogs in the project (`react-bootstrap` is used to display modal dialogs throughout the app - things like the help file, the image answer pop-ups, etc.).  This bug is caused by a change/issue in the dialog animation in the new version of the library.  The dialog position and opacity are left in the initial, pre-animation states (opacity = 0, position is hidden) instead of transitioning to their displayed states.  There isn't an obvious reason why this is happening after initially reviewing our implementation.  The same occurs when using the example modal dialogs in our project:
https://react-bootstrap.github.io/components/modal/
One option is to downgrade …
=> Fix modal dialogs

css/portal-dashboard/all-responses-popup/popup-header.less, cypress/integration/portal-dashboard/portal-dashboard-all-responses-popup.spec.js, cypress/integration/portal-dashboard/portal-dashboard-question-details.spec.js, cypress/integration/portal-dashboard/portal-dashboard-smoke-test.spec.js, js/components/portal-dashboard/all-responses-popup/popup-header.tsx, js/components/portal-dashboard/class-nav.tsx, js/components/portal-dashboard/question-overlay.tsx
This PR removes the feedback toggle in the upper left nav area, the feedback button in the student responses popup, and the class response section in the question overlay as we prepare for an MVP version of the new portal dashboard.  Code has been commented out in several cases with a "Removed for MVP" tag so we can more easily add it back in later.
=> 174390612 hide feedback and class response UI elements

css/portal-dashboard/answer.less, css/portal-dashboard/overlay-student-response.less
Add a minimum size to the answer component and add scroll bars when needed so content is always displayed in question overlay panel.
=> Set min-size and add vertical scrolling to answer component

css/portal-dashboard/level-viewer.less
Use ellipsis when the level viewer activity text is expanded and overflows. There are probably other places in the app where this is needed, but this gives us a starting point.
=> Use ellipsis when level viewer activity text is expanded and overflows

css/portal-dashboard/all-responses-popup/popup-class-nav.less, css/portal-dashboard/all-responses-popup/popup-student-response-list.less, css/portal-dashboard/answer.less, css/portal-dashboard/answers/image-answer.less, css/report/iframe-answer.less, cypress/integration/portal-dashboard/portal-dashboard-all-responses-popup.spec.js, js/components/portal-dashboard/all-responses-popup/popup-student-response-list.tsx, js/components/portal-dashboard/answers/image-answer.tsx, js/components/portal-dashboard/overlay-student-response.tsx, js/components/report/iframe-answer.js, js/containers/portal-dashboard/answer.tsx, js/util/answer-utils.ts
This PR makes fixes to the handling of the interactive iframe answers and some small UI improvements to the all student responses overlay.  Changes include: 
- Correctly determine if interactive can be opened with "View Work" link or only with "View work in new tab" link.
- Better handling of interactive sizing in question overlay (improvements to both the image answer and the interactive answer).
- Fix the min height of answers in the all student responses overlay (min height was being applied at all times which was adding lots of unneeded whitespace).
- Fix background color in upper left nav in all student responses (fixes the white band that sometimes appeared at bottom of nav component).
- Fix student name column width in all student responses (the column width did not line up with …
=> 174390484 interactive iframe

css/portal-dashboard/answer-compact.less, css/portal-dashboard/overlay-student-response.less, cypress/integration/portal-dashboard/portal-dashboard-question-details.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-table.spec.js, js/actions/dashboard.js, js/components/portal-dashboard/overlay-student-response.tsx, js/components/portal-dashboard/question-overlay.tsx, js/components/portal-dashboard/student-answers.tsx, js/containers/portal-dashboard/answer-compact.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/reducers/dashboard-reducer.ts, js/selectors/dashboard-selectors.js, js/util/answer-utils.ts, test/reducers/dashboard-reducer_spec.js
This PR fixes a bug/unimplemented feature in the response table.  When an response table icon is clicked, the current question and student in the question overlay need to change state to reflect the item that was clicked on.  This PR adds a current student index to the to redux state so that we can access a current student in parallel components.  Otherwise, existing redux state is used to manage clicks in the response table.
=> Response table selection

js/containers/portal-dashboard/answer.tsx
This PR adds unique keys to the answer containers in the question overlay.  This should guarantee that when navigating to a new student or question, React will flush the answer node and creates a new component where we can properly initialize the interactive iframe.  This is hard to verify without the new mock data.  However, barring any obvious issues, I suggest that we merge this and then rebase the mock data branch onto master where we can confirm the fix.
=> Fix interactive load error when navigating from one interactive to another

js/containers/portal-dashboard/portal-dashboard-app.tsx
Set the tab title to "Class Dashboard" when the new portal dashboard is launched.
=> Set portal dashboard tab title

js/containers/portal-dashboard/portal-dashboard-app.tsx
This PR fixes a bug in the handling of the scroll state.  When the horizontal scroll offset was 0, we were not saving the state due to a faulty comparison.   Instead explicitly test against undefined so that we save the scroll offset when it is 0.
=> Fix handling of scroll state when scrollLeft is 0

css/portal-dashboard/question-navigator.less, js/components/portal-dashboard/question-navigator.tsx
This PR fixes the UI of the show//hide question arrow button in the question overlay so that it matches the UI spec.  Changes include:
- proper arrow orientation.  Arrow points up when question is shown, points down when question is hidden
- arrow has correct color when question is hidden
- arrow has hover states defined in UI spec
See spec for more details:
https://app.zeplin.io/project/5e96f4b8527afa7d28bb1468/screen/5ed4f976e9fe2773c0bd3a33
=> Fix arrow button states

css/portal-dashboard/header.less, css/portal-dashboard/level-viewer.less, css/portal-dashboard/student-answers.less, css/portal-dashboard/student-names.less, cypress/integration/portal-dashboard/portal-dashboard-scrolling.spec.js, js/components/portal-dashboard/student-answers.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx
This PR makes changes to the display of the horizontal scroll bar for the response table when the app is at a short width.  The primary change being ensuring that the scrollbar is always visible when the content overflows (previously could be hidden if the vertical scrollbar was also present and the user was scrolled to the top of the container).  Changes include:
- Always show the horizontal scrollbar when it is needed
- Improve responsiveness of app header by adjusting the flex layout - this allows the header to behave better when the app width is small
- Improve the display of the vertical scrollbar and top border of first student row (move cover so we do not occlude these controls)
=> 174831493 horizontal scroll improvements

css/portal-dashboard/all-responses-popup/popup-class-nav.less, js/components/portal-dashboard/all-responses-popup/popup-class-nav.tsx, js/components/portal-dashboard/all-responses-popup/spotlight-message-dialog.tsx, js/components/portal-dashboard/all-responses-popup/spotlight-student-list-dialog.tsx, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx
Adds more sophisticated state management of the spotlight dialog.  We previously assumed that if the number of selected students was 0, that we could always show the spotlight message dialog.  This is incorrect, a user can remove all of the selected students inside the spotlight list dialog itself which then keeps the spotlight list dialog up but with no student showing.  I wasn't eager to introduce another state variable, but I think this is the most straightforward way to handle this other than merging the dialogs into a single component.
=> Improve handling of spotlight dialogs

js/components/portal-dashboard/all-responses-popup/popup-student-response-list.tsx, js/components/portal-dashboard/all-responses-popup/spotlight-student-list-dialog.tsx, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx
This PR changes how we store the currently selected set of spotlight students in the `StudentResponsePopup` component state.  Previously we stored  an array of students (where students was an immutable JS map, the same way that students are stored in the Redux state).  These changes make it so that we now store an array of student id strings in the component state.
It wasn't immediately obvious why this change was needed, but there was a bug in the anonymized name that appeared in the student spotlight.  This made it clear that our previous component state model was incorrect.  Previously, when a student was selected for spotlight, we grabbed a copy of the student (again, an immutable JS map) from the Redux state and stored that in our component state.  However, after the student state in …
=> Update stored spotlight state to use student ids and not student map

css/portal-dashboard/questions/multiple-choice-question.less, js/components/portal-dashboard/questions/multiple-choice-question.tsx
This PR fixes a bug that caused the multiple choice bubble to display incorrectly when we have long text in the multiple choice question.  Changes include:
- fix bug so bubble displays properly
- reduce margin so we have more space to display question
- remove undefined `mcContent` class that we were adding to the question text
=> Fix multiple choice question layout

css/portal-dashboard/all-responses-popup/spotlight-student-list-dialog.less, js/components/portal-dashboard/all-responses-popup/spotlight-student-list-dialog.tsx, js/components/portal-dashboard/question-area.tsx
This PR fixes two bugs in the spotlight view:
- The app crashed when opening an interactive question in the spotlight.  This was caused by an empty prompt in the question.  I expanded the checks for what text to display for the question in the spotlight, but @eireland you did much of the work that decides which question text to display in which context.  You might want to confirm my text choices.
- The vertical size of the content container in the spotlight view was incorrect.  It didn't fill the entire space of the spotlight view.  As a side note, I would avoid using the CSS `calc` with the viewport height/width (`vh` and `vw`) unless absolutely needed.  It tends to lock us into complex calculations that depend upon other component sizing when simple flex containers can often do the work …
=> Fix crash in spotlight

js/components/portal-dashboard/level-viewer.tsx, js/components/portal-dashboard/question-overlay.tsx
This PR makes changes so that after clicking on an activity button in the Level Viewer, we clear the current selected question and hide the Question Overlay.  This adheres to the Dash Prototype (https://hav7ta.axshare.com/#id=nkd8s4&p=portal_dashboard___reports_v3_4), and fixes some of the odd states that a user can get into in the app.  Without this fix, the following can happen:
- User has activity1: question1 showing in Question Overlay.  User clicks on activity2 in the Level Viewer.  We still display activity1: question1 in the Question Overlay even though the user has selected activity2.  
- User has Question Overlay showing.  User clicks activity button in Level Viewer to collapse the current activity (now NO activity is selected).  User now presses the Show All Students buttons. …
=> Toggle current activity and close question overlay when click activity in level viewer

js/components/portal-dashboard/all-responses-popup/popup-class-nav.tsx, js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx, js/components/portal-dashboard/class-nav.tsx, js/components/portal-dashboard/custom-select.tsx, js/components/portal-dashboard/header.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/selectors/dashboard-selectors.js
This PR syncs the state of the two student sort `CustomSelect` component instances within the app.  Unlike other occurrences of the `CustomSelect` where the selected item is managed by the component's local state, if the current sort method is changed in one `CustomSelect`, it must also be changed in the other instance (this is similar to what we needed to do with the 3(!) anonymize toggles in the app - they all have to have a synchronized state).  To do this, we obtain the current student sort method from the Redux component and pass it to the `CustomSelect`.  This allows the `CustomSelect` to use or override its internal component state management based on the absence or presence of an optional prop.
There is also some minor refactoring of component props lists.  As the props lists grow …
=> 174915493 student sort

js/components/portal-dashboard/all-responses-popup/student-responses-popup.tsx
As per the design discussion, this PR clears the set of spotlighted students when the user navigates to a new question in the All Student Responses view.
=> Reset spotlighted students when change question

css/portal-dashboard/level-viewer.less, cypress/integration/portal-dashboard/portal-dashboard-scrolling.spec.js, js/components/portal-dashboard/all-responses-popup/popup-header.tsx, js/components/portal-dashboard/level-viewer.tsx, js/global.d.ts, package-lock.json, package.json
This PR fixes two cases where long, overflowing text was not being handled properly.  In both cases overflow text should be shown with a set number of lines and with ellipsis as per the UI spec.  Cases include:
- activity names in the buttons in the level viewer
- activity name in the all student responses view
For anyone interested, I used the library `react-lines-ellipsis` to handle multi-line overflow (which is much trickier than single line overflow with ellipsis).  I also tried `react-clamp-lines` (I couldn't get the sizing and number of clamped lines to work) and `React-clamp` (old, didn't work at all).
=> 174962304 text overflow

css/portal-dashboard/all-responses-popup/popup-student-response-list.less, css/portal-dashboard/all-responses-popup/student-responses-popup.less, css/portal-dashboard/question-area.less
Improve handling of long question text in both the question overlay and all student response views.
=> Fix question area height in question overlay and all student responses

cypress/integration/api-error.spec.js, js/actions/index.ts, js/api-middleware.js, js/api.ts, js/db.ts, js/reducers/data-reducer.ts
This changes the 'fake' mode for runKey based testing of the report.
It now tries to load the answer documents for real.  This way the tests exercise more of the code.
It does mean when a runKey is specified, then no answers are shown, however if the point of the test is to work with the answers then it should just leave off the runKey param.
It also moves the disableNetwork into db.ts This seems like a more natural place to put this. 
Additionally, it adds a test for the showing of network errors. This uncovered a bug in the code where the Immutable Record was being initialized without a `error` property. And as far as I understand Immutable Records need to be initialized with all possible properties. It doesn't allow `set(..)` calls unless the properties are defined. So the code was …
=> Improve anonymous tests

css/portal-dashboard/question-overlay.less, css/portal-dashboard/variables.less, cypress/integration/portal-dashboard/portal-dashboard-question-details.spec.js, js/components/portal-dashboard/question-overlay.tsx
Update the all responses button in the question overlay to match the UI spec.  Changes includes:
- move all responses button to question detail header
- remove all responses button from footer (entire footer should be removed)
- update colors in all responses button (button state colors should change from teal to orange)
- update related text. "View All Student Responses" becomes "View All Responses" and "Question Detail View" becomes "Question Details".
=> Update all responses button in question overlay

css/portal-dashboard/header.less, js/actions/dashboard.js, js/components/portal-dashboard/header-menu.tsx, js/components/portal-dashboard/header.tsx, js/components/portal-dashboard/student-answers.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/reducers/dashboard-reducer.ts, js/selectors/dashboard-selectors.js, test/reducers/dashboard-reducer_spec.js
This PR makes adjustments to the upper right menu:
- change show feedback badges to hide feedback badges (needed to change underlying state as well)
- turn on the feedback badges menu item (will be needed when we implement feedback)
- hid feedback badges and compact menu items if we are on any view other than the progress view
=> Change show feeback to hide feedback, fix menu options

css/portal-dashboard/activity-navigator.less, css/portal-dashboard/question-area.less, css/portal-dashboard/question-navigator.less, css/portal-dashboard/response-details/response-details.less, cypress/integration/portal-dashboard/portal-dashboard-response-details.spec.js, js/components/portal-dashboard/activity-navigator.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx
Adds ability to navigate from one activity to another while in response detail view and content is a sequence.
If user goes directly to response view without selecting a student or a question, the navigator defaults to the first question in the first activity. Otherwise it will go to the selected question.
When a user navigates between activities, the question shown is always the first question in the activity.
When content is a single activity, activity navigator is not shown.
=> 176082067 activity navigator

README.md, cypress/integration/portal-report-smoke-test.spec.js, cypress/support/elements/portal-report/report-body.js, js/actions/index.ts
User can now add `resourceType=activity` query param to show activity resource and answer. It defaults to showing sequence data if query param is not present.
This should make it easier to switch between fake sequence and fake activity data without having to change it in code.
=> Adds ability to show fake activity data with query param

cypress/integration/anonymous-user-report.spec.js, docs/launch.md, docs/report-service.md, docs/source-key.md, js/actions/index.ts, js/api-middleware.js, js/api.ts, js/components/portal-dashboard/question-navigator.tsx, js/db.ts, js/index.js, js/util/misc.ts, test/api_spec.js, test/db_spec.js
Summary of changes:
We are redirecting with `window.location.assign(...)`, this doesn't stop the current javascript from executing. So if we do that redirect then `initializeAuthorization` returns `true`, and the main app is not rendered. See the changes in `js/index.js`.
Previously the firestore database was initialized immediately in `js/db.ts`. Now it is only initialized if we aren't redirecting. 
The previous code would store a promise which resolved to the firestore db and exported `firestoreInitialized`. The other code would chain promises off of that. This way those chained promises would not run until the database was fully initialized. Now `firestoreInitialzed` is replaced with `getFirestore()`. The method returns a promise that resolves to the firestore db like …
=> Logged in user report part 2

js/api.ts, test/api_spec.js
this was causing problems when testing because we had no token in the url
so getAuthHeader was throwing an error
This can be tested with:
http://portal-report.concord.org/branch/fix-error-with-feedback/?enableFirestorePersistence=true
To track down this really simple change, I improved the error handling, and I put that in a different PR:
https://github.com/concord-consortium/portal-report/pull/286
=> fix local feedback testing

cypress/integration/api-error.spec.js, cypress/integration/geode-dashboard-smoke-test.spec.js, cypress/integration/portal-dashboard/portal-dashboard-question-details.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-details.spec.js, cypress/support/elements/portal-report/feedback.js, cypress/support/elements/portal-report/header.js, cypress/support/elements/portal-report/report-body.js, js/api-middleware.js, js/api.ts, js/components/report/data-fetch-error.js, package-lock.json, package.json, test/api_spec.js, test/components/report/data-fetch-error_spec.js
Runtime changes:
- callAPI now handles errors thrown during promise evaluation or when an api function throws an error before returning the promise.
- APIError now extends Error which provides stack traces at the location the error was generated. Extending Error can be problematic because it breaks instanceof checks. That happens due to transpiling. Several articles on this, here is one example: https://www.bennadel.com/blog/3226-experimenting-with-error-sub-classing-using-es5-and-typescript-2-1-5.htm
- to work around the instanceof check above, now the name property is used instead of instanceof to identify APIError objects.
- remove the re-throwing of the error since we are already printing it to the console. There might be edge
cases where some un handled error happens during the …
=> fix several issues with the api error handling

js/components/portal-dashboard/feedback/activity-feedback-textarea.tsx, js/components/portal-dashboard/feedback/feedback-question-rows.tsx, js/components/portal-dashboard/feedback/question-feedback-textarea.tsx, js/components/portal-dashboard/feedback/question-level-feedback-student-rows.tsx
This PR adds the review flag when submitting feedback which allows us to determine if feedback has been submitted and it it needs to be updated by examining the feedback in the Redux state.  Although feedback was being submitted to the student, we we're marking these internal feedback flags.
=> Add feedback review flags

css/portal-dashboard/feedback/feedback-rows.less
PT Story: https://www.pivotaltracker.com/story/show/176083561
[#176083561]
This removes the manual resize option for the input fields per the PT story note that says if manual resizing adds complexity, only use the dynamic, responsive option.
=> Remove manual resize option for input fields.

css/portal-dashboard/header.less, css/portal-dashboard/level-viewer.less, css/portal-dashboard/portal-dashboard-app.less, css/portal-dashboard/progress-view-legend.less, css/portal-dashboard/response-details/popup-student-response-list.less, css/portal-dashboard/response-details/response-details.less
PT Stories: 
https://www.pivotaltracker.com/story/show/176649578
https://www.pivotaltracker.com/story/show/176648006
[#176649578]
[#176648006]
* Allow user to scroll horizontally to view content that was being cut off.
* Prevents progress view legend from being overlapped by other elements.
=> Some content inaccessible in narrow viewports

cypress/integration/portal-dashboard/portal-dashboard-student-sort.spec.js, js/actions/dashboard.js, js/components/portal-dashboard/response-details/response-details.tsx, js/containers/portal-dashboard/popup-class-nav.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/reducers/dashboard-reducer.ts, js/selectors/dashboard-selectors.js, test/reducers/dashboard-reducer_spec.js
This PR splits the feedback sort and progress/response sort into two unique pieces of Redux state.  This allows us to keep two different sort lists that are displayed to the user.
=> 176599991 feedback sort

js/actions/index.ts, test/actions/index_spec.js
The regex was returning the last id digit instead of all the id digits.  This wasn't caught in the test coverage as the tests all used single digit ids.
=> Fix bad regex in resource url parser

js/actions/index.ts, js/reducers/report-reducer.ts, test/reducers/report-reducer_spec.js
Adds the username in the form of `<userid>@<domain>` to the report state so that it can used when logging
=> Add logging username to report state

css/portal-dashboard/response-details/popup-class-nav.less, js/actions/dashboard.js, js/components/portal-dashboard/feedback/activity-feedback-textarea.tsx, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/feedback-question-rows.tsx, js/components/portal-dashboard/feedback/question-feedback-textarea.tsx, js/components/portal-dashboard/feedback/question-level-feedback-student-rows.tsx, js/containers/portal-dashboard/feedback/activity-feedback-panel.tsx, js/containers/portal-dashboard/feedback/question-feedback-panel.tsx, js/containers/portal-dashboard/popup-class-nav.tsx, js/reducers/dashboard-reducer.ts, js/selectors/dashboard-selectors.js, test/reducers/dashboard-reducer_spec.js
This PR updates the enabled/disabled state of the awaiting feedback refresh button.  State is maintained in Redux and passed to components as needed.  Changes include:
- add Redux state to keep track of refresh button enabled state
- when refresh button is pressed, disable button
- when feedback is changed, enable button
- when change between awaiting feedback and student name sort, disable button
- hide button if in student name sort mode
The next step will be to have the button click update the sort.  This will require feedbacks keeping track of if they have been modified since the last sort.
=> Awaiting Feedback Refresh button state

css/portal-dashboard/response-details/response-details.less, cypress/integration/portal-dashboard/portal-dashboard-student-sort.spec.js, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/rubric-table.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/containers/portal-dashboard/feedback/activity-feedback-panel.tsx, js/selectors/dashboard-selectors.js
This PR adds the following changes and fixes to the activity feedback sort:
- display sorted activity feedback when awaiting feedback sort is used
- fix bug in activity awaiting feedback sort where all activities were checked for feedback, need to use current or first
- fix bug in activity awaiting feedback sort where unstarted activities were not sorted properly
- update refresh button state when rubric is selected
- update container height
NOTE that with these changes as soon as activity feedback is entered, the feedback will be sorted to the bottom of the list. This will be fixed in upcoming work.
=> 176492325 feedback fixes

cypress/integration/portal-dashboard/portal-dashboard-student-sort.spec.js, js/components/portal-dashboard/feedback/activity-feedback-textarea.tsx, js/components/portal-dashboard/feedback/question-feedback-textarea.tsx, js/components/portal-dashboard/feedback/rubric-table.tsx, js/components/portal-dashboard/response-details/response-details.tsx, js/containers/portal-dashboard/answer-compact.tsx, js/containers/portal-dashboard/feedback/activity-feedback-panel.tsx, js/containers/portal-dashboard/feedback/question-feedback-panel.tsx, js/containers/portal-dashboard/popup-class-nav.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/selectors/dashboard-selectors.js
This PR updates the awaiting feedback search.  Changes include:
- add question sort, implemented in `getQuestionFeedbackSortedStudents`
- when refresh button is pressed or sort is changed, mark existing feedback since last sort with `existingFeedbackSinceLastSort` flag so sort knows which feedback has been added since the last sort (and can treat the feedback as if it were empty)
- improve handling of empty string feedbacks (most likely caused by deletion)
- fix Cypress tests
=> 176492325 question sort refresh button

js/components/portal-dashboard/response-details/response-details.tsx
This PR fixes the following bug:
- when the user opens the response details view, we check to see if there is a current activity and a current question.  If either is undefined, we get the first activity and/or the first question and display that to the user.  However, this neglects an important case.  A user can have a current activity (done by simply clicking on an activity in the level viewer) but NO current question.  In this case, it is not sufficient to simply get the first question, but instead we must get the first question _of the current activity_.  Otherwise, if, for example, the current activity was activity 2 and there was no current question, we would display the first question of activity 1.  This change ensures that we get a question that corresponds to the current …
=> Fix handling of first question in response details when no question is selected

js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx
Bug was when user clicked on Activity toggle in feedback view, the page would turn blank. This was because it would fail when there was no rubric feedback.
This PR adds a check to see if there is rubric feedback before trying to check if rubric feedback had been given.
=> Fix activity level feedback view when there is no rubric

cypress/integration/portal-dashboard/portal-dashboard-expand-activities.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-details.spec.js, js/components/portal-dashboard/level-viewer.tsx, js/components/portal-dashboard/question-area.tsx, js/components/report/page.js, js/core/transform-json-response.ts, js/data/sequence-structure.json, test/core/transforom-json-response_spec.js
the preview_url was added to support activity player runtime activities
the url of the activity in the resource structure needed to stay pointing at the LARA runtime
so the resource structure document could be found during Firestore queries,
the preview_url is optional so we don't need to go and update existing report-structures that
have already been published to Firestore.
TODO
=> support preview_url in report-structure

js/components/portal-dashboard/class-nav.tsx
Removes a redundant colon from class nav student label
=> Removes second colon in class-nav

js/util/misc.ts, test/util/misc_spec.ts
This PR fixes a bug that caused valid image question feedback to sporadically be hidden.  This was caused by a mismatch between the answer hash stored with the feedback and the answer hash created in the dashboard from the current image question answer - this mismatch caused us to hide the feedback (thinking that it was out of date because the answer had changed).  Even when the user-facing image question answer has not changed, the stored structure of the answer can change.  Most answers are simple text strings.  However, the image question answer is stored as an Immutable JS `Map` with two keys: `image` and `text`.  Depending on how that `Map` was created, we would sometimes get the `image` key first and sometimes get the `text` key first.  In other words, the key order was not …
=> Order map keys when generating answer hash to ensure repeatable hash results

css/portal-dashboard/response-details/response-details.less
This PR fixes the question nav height in the response details view when there is only a single activity.
=> Fix question nav height

js/actions/index.ts, js/api.ts, js/components/report/interactive-iframe.js, test/api_spec.js
This uses the new portal researcher JWT support,
and the new report-service researcher support.
It does this by passing a target_user_id parameter to the portal's firebase JWT endpoint.
And it now passes the studentId param into the firestore queries.
This is needed so the firestore rules can only allow access to a specific student
based on the JWT issued by the portal.
This might also speed up the per student report since it will limit the number of answers returned.
=> Add researcher support

cypress/integration/geode-dashboard-smoke-test.spec.js, cypress/integration/portal-dashboard/portal-dashboard-question-details.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-table.spec.js, cypress/integration/portal-dashboard/portal-dashboard-student-sort.spec.js, cypress/integration/portal-report-smoke-test.spec.js, js/components/portal-dashboard/answers/image-answer.tsx, js/components/report/answer.js, js/components/report/image-answer.js, js/components/report/image-question-details.js, js/data/answers.json, js/util/answer-utils.tsx, js/util/misc.ts, test/util/misc_spec.ts
The AP is occasionally saving image question documents that don't have an answer field. This was breaking the portal-report.
The changes in this PR handle this case by showing and error message for this particular student answer. The once case that isn't handled well is in the standard report image carousel. In that case with a broken answer just a blank image is shown. Because we are trying to move away from the standard report, and this should only happen in error cases it seems fine to leave this broken.  If a teacher is curious and then show the responses then they will see the error message.
Here is what the standard report looks like:
In the portal dashboard "progress dashboard"
In the portal dashboard "response details":
https://www.pivotaltracker.com/story/show/179406265
=> Handle errors in image question documents

js/api.ts, test/api_spec.js
This PR removes the function `updateReportSettingsInPortal` which is no longer used and was causing errors when accessing user feedback (a PUT request with an updated feedback object was being sent to an invalid URL causing a 404 error).  Feedback is uploaded to Firestore, but no longer needs to be uploaded to the portal.
=> remove obsolete updateReportSettingsInPortal

cypress/integration/portal-dashboard/portal-dashboard-expand-activities.spec.js, cypress/integration/portal-dashboard/portal-dashboard-question-details.spec.js, js/components/portal-dashboard/answers/answer-modal.tsx, js/components/portal-dashboard/answers/image-answer.tsx, js/components/portal-dashboard/level-viewer.tsx, js/components/portal-dashboard/question-area.tsx, js/components/portal-dashboard/response-details/spotlight-student-list-dialog.tsx, js/containers/portal-dashboard/answer.tsx, js/data/sequence-structure.json, js/util/question-utils.ts
This also fixes an issue where the question has an unknown type.
in that case it uses the iframe_interactive icon.
There are couple of logic changes here that I'm not sure about:
- in answer-modal, it was using the answer's questionType, the types seem to imply that sometimes the question can be undefined. So this might be why the answer's questionType is used. However it makes no sense to me that there'd be an answer without a question. So this case of an undefined question seems like an error edge condition. I didn't try to track down when that case happens, so possible it is a common case and should be handled better
- in spotlight-student-list-dialog, the fact that the question is scored or not, was being ignored when looking up the icon. I assumed this was an oversight, but perhaps …
=> move question icon logic to question-utils

js/containers/portal-dashboard/popup-class-nav.tsx
When feedback is turned on, opening the response details or feedback report crashes portal report when some students have not received feedback for a question. We were trying to trim a feedback that didn't exist. 
This adds a check to see if feedback existed before trying to trim it.
=> fix crash when there is no feedback

css/portal-dashboard/feedback/feedback-rows.less, css/portal-dashboard/portal-dashboard-app.less, css/portal-dashboard/response-details/response-details.less
This fixes the response details container height so that all of the student response and feedback rows can be accessed with scrollbars when the content doesn't fit vertically.
PT Story:
https://www.pivotaltracker.com/story/show/179810273
=> Fix response details height (179810273)

cypress/integration/standalone-iframe.spec.js, js/actions/index.ts
- Asserts that runKey will be used to lookup platformUserId if the `studentId` param is missing.
- Had to add a new url param `_useFakeDataForTest` because the presnense of `runKey` was triggering FireStore lookups.
PT Story: [#180446631](https://www.pivotaltracker.com/n/projects/2441249/stories/180446631)
=> 180446631 - Cypress test for iframe-standalone for anonymous users

css/portal-dashboard/response-details/popup-student-response-list.less, js/components/portal-dashboard/response-details/popup-all-student-response-list.tsx
This was broken when the flex direction was changed to support the report-item interactives.
=> Fix checkbox position under response details [#181037903]

css/report/iframe-answer.less, cypress/integration/standalone-iframe.spec.js, js/components/report/iframe-answer.tsx, js/containers/report/iframe-standalone-app.js
PT Story: https://www.pivotaltracker.com/story/show/181154848
[#181154848]
Adds a URL param for standalone iframes that can be used by question interactives to determine whether they should or shouldn't be scaled to fit the confines of the report/dashboard. Also makes some CSS adjustments to help handle scaled interactives.
These changes go along with [these related changes in question-interactives](https://github.com/concord-consortium/question-interactives/pull/163) and [these changes in LARA](https://github.com/concord-consortium/lara/pull/909).
=> Fix drag-and-drop interactive does not look correct in report/dashboard.

css/report/iframe-answer.less
PT Story: https://www.pivotaltracker.com/story/show/181154848
[#181154848]
Tweaks style rules to ensure proper scaling of interactive and that the entire scaled interactive is visible in the Response Details view in the dashboard. Without these changes, the drag-and-drop interactive was cut off a little at the bottom, and the side-by-side interactive wasn't being scaled down properly.
=> Fix drag-and-drop and side-by-side scaling in reports.

js/containers/portal-dashboard/answer-compact.tsx, js/containers/portal-dashboard/answer.tsx, js/util/answer-utils.tsx
PT Story: https://www.pivotaltracker.com/story/show/181223927
[#181223927]
The dashboard should always show "No response" when a student has left neither audio nor a written response to an open response question with audio enabled. If a student leaves only an audio response, the dashboard should show a button/link to play the audio, and the text "No written response". If a student only leaves a written response, the dashboard should show only the text response (no playback button, no message about there being no audio).
Without these changes, the dashboard would show "No written response" when a student left neither audio nor a written response. This is because open response questions with audio enabled will still have an answer set even when the student didn't provide a written or audio …
=> Fix Playback Audio Answers in Class Dashboard

css/report/iframe-answer.less
This moves the max-height from the enclosing container to the iframe content.  Without this the links were being hidden by the expanded iframe content.
=> Fix view work/open in new tab links disappearing [#182562269]

cypress/integration/portal-dashboard/portal-dashboard-expand-activities.spec.js, cypress/integration/portal-dashboard/portal-dashboard-question-details.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-table.spec.js, js/containers/portal-dashboard/answer-compact.tsx, js/data/answers.json, js/data/sequence-structure.json, s3_deploy.sh, s3_website.yml
This removes the report item urls from the other interactives.
This makes it possible to test the other interactives the normal way.
It also updates the version of the generic report item interactive. Old version of the report item interactive didn't handle the update API.
So this fixes a crash that happened when viewing the student work of many of the interactives in the demo data in A2.
=> add interactive question for report item

js/api.ts, js/components/portal-dashboard/question-area.tsx, js/core/transform-json-response.ts, package-lock.json, test/core/transforom-json-response_spec.js
[#181821831]
This PR adds auth-domain URL param to AP Teache Editon links.
It's related to: https://github.com/concord-consortium/activity-player/pull/378
I've also added rollover text to this button, which is a separate story, but touches the same code.
=> Launch AP Teacher Edition with auth-domain param

js/components/report/iframe-answer.tsx
PT Story: https://www.pivotaltracker.com/story/show/182994863
[#182994863]
These changes address issues revealed when adding bar graph sparklines to the Sensor Interactive report item.
* `IframeAnswer`'s `renderLink` function needs to be bound.
* Wrap `IframeAnswer` links in a containing DIV so they're not treated as flex items which wrap to multiple lines.
Required by [this PR](https://github.com/concord-consortium/sensor-interactive/pull/118).
=> Bar graphs in reports / class dashboard

js/components/portal-dashboard/response-details/response-details.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx
This fixes the feedback level being reset to the initial state when the response details page is re-mounted by moving the feedback level up to the top app state.
=> fix: Lifted feedback level state up to app state [PT-187132915]

js/components/portal-dashboard/response-details/response-details.tsx, js/containers/portal-dashboard/popup-class-nav.tsx
This ensures we don't have a disabled view shown when we switch to the feedback view.
=> fix: Autoselect the question feedback when the response details view is set to question [PT-187132915]

js/util/scoring.ts
When a score is removed from the rubric the value is set to 0 and in that case the scored question count should not be increased.
=> fix: Average rubric score calculation [PT-187021319]

css/portal-dashboard/feedback/feedback-legend.less, css/portal-dashboard/feedback/rubric-summary-icon.less, css/portal-dashboard/feedback/rubric-summary-modal.less, css/portal-dashboard/feedback/rubric-table.less, js/components/portal-dashboard/feedback/feedback-legend.tsx, js/components/portal-dashboard/feedback/rubric-summary-icon.tsx, js/components/portal-dashboard/feedback/rubric-summary-modal.tsx, js/components/portal-dashboard/feedback/rubric-utils.ts
Features:
- Rubric summary icon shows the distribution of scores per aspect of proficiency across the class in the Feedback Panel
- Icon updates as scores are entered
- If no rubric scores are entered, show N/A in place of the rubric icon in the feedback panel
- Rubric summary icon has default, hover, and click states
- When clicked, display lightbox dialog of Rubric Summary Details that shows percentages across the class per rating
=> feat: Add rubric icon and details dialog [PT-187021082]

js/components/portal-dashboard/feedback/feedback-legend.tsx, js/components/portal-dashboard/feedback/feedback-settings-modal.tsx, js/components/portal-dashboard/feedback/feedback-settings-toggle.tsx
This adds a confirmation dialog if the max score is set to be less than existing student scores.
=> feat: Add confirmation on max score setting [PT-187021265]

css/portal-dashboard/feedback/show-student-answers.less, img/svg-icons/expand-more-icon.svg, js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/portal-dashboard/feedback/show-student-answers.tsx, js/containers/portal-dashboard/feedback/activity-feedback-panel.tsx
As a teacher, I want to view all answers to an activity per student when providing activity-level feedback in the class dashboard.
Acceptance Criteria:
- Below the feedback text field in each student's row, display a Show Student Answers button
- When clicked, the text on the button changes to Hide Student Answers and the row expands to display an iframe of the student's answers to that activity.  User can scroll within the iframe of student answers to view all questions & answers
- Default is collapsed / student answers hidden
- Buttons have default, hover, and select states
=> feat: Show student answers in feedback [PT-187021149]

js/components/portal-dashboard/feedback/activity-feedback-score.tsx, js/components/portal-dashboard/student-answers.tsx, js/selectors/activity-feedback-selectors.js
Before this the score defaulted to 0.  With this change the scores default to undefined and when a score value is cleared the score is deleted from Firebase.
=> feat: Allow deletes of manual scores [PT-187021265]

js/actions/index.ts, js/components/portal-dashboard/feedback/activity-feedback-score.tsx
This fixes two issues:
1. Empty score values were not being logged.  A new logEmptyLabel option was added to support this.
2. The score value was always being logged when blurred instead of only logging when the score changed on blur.
=> fix: Logging of empty and duplicate score values [PT-187192076]

js/components/portal-dashboard/feedback/feedback-settings-modal.tsx, js/components/portal-dashboard/feedback/rubric-summary-icon.tsx
- Only display max score modal when the user switches to the Manual score setting
- Rubric summary should only display student scores from complete rubrics
=> fix: Fit n' finish fixes [PT-187186199]

js/components/portal-dashboard/feedback/feedback-settings-modal.tsx, js/util/scoring.ts
The feedbacks.scores attribute is not updated in the selector when the question changes so the scores need to be pulled from the individual student feedback which does change when the question is changed.
=> fix: Pull manual scores from feedbacks and not higher level scores attribute [PT-187021319]

cypress/integration/portal-dashboard/portal-dashboard-activity-score.spec.js, cypress/support/elements/portal-report/activity-score-settings.js
Activity Score Settings Automation Coverage
=> Activity Score Automation

css/portal-dashboard/header.less, js/components/portal-dashboard/header.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/core/transform-json-response.ts, js/data/small-class-data.json, js/reducers/report-reducer.ts, js/selectors/activity-feedback-selectors.js, js/selectors/compare-view-data.js, js/selectors/dashboard-selectors.js, js/selectors/report.js, js/util/misc.ts
This adds a secondary header element if the user is a researcher.  This new element displays under the main header and shows that the interface is in researcher mode and displays the class name and teacher names.
The teachers of the class were previously not storied in the state so most of the work of this commit is adding that to the state and drilling it down as a prop.
=> feat: Add secondary researcher header element [PT-187325112]

js/components/portal-dashboard/header.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/core/transform-json-response.ts, js/data/small-class-data.json, js/reducers/report-reducer.ts, js/selectors/activity-feedback-selectors.js, js/selectors/compare-view-data.js, js/selectors/dashboard-selectors.js, js/selectors/report.js, js/util/misc.ts
This removes the teachers names that were part of the initial new researcher sub-header as they are already displayed in the top right corner of the app.
Most of this PR is to remove the teachers from the state, which was added to show the teacher names in the header.
=> fix: Remove newly added teacher names to researcher header [PT-187325112]

css/portal-dashboard/header.less, css/portal-dashboard/portal-dashboard-app.less, css/portal-dashboard/variables.less, js/containers/portal-dashboard/portal-dashboard-app.tsx
The response details and feedback views use fixed elements under the header and have a top value set which was covering up the optional researcher header.
This also fixes the bottom 3px white border (defined using a bottom-margin) disappearing when the user switched out of the progress dashboard.
=> fix: Show researcher header outside progress dashboard view [PT-187325112]

js/containers/portal-dashboard/answer-compact.tsx, js/util/answer-utils.tsx
Previously the audio answer badge check looked at the attachments and if there was at least one audio attachment the badge was shown.  This was found to be incorrect in QA as when the audio is deleted the attachment remains but the interactive state is updated to remove the pointer to the attachment.
This commit changes to look at the interactive state within the report state.
This also fixes a missing key issue in the audio badges display that causes a warning.
=> fix: Change audio answer badge check [PT-187279104]

js/db.ts
Obfuscated Firebase API key using atob() so that automated key leak detectors are not falsely triggered.
NOTE: the Firebase API key is a public key so this does not leak secrets.
=> chore: Obfuscated Firebase API key [PT-187643494]

js/components/report/feedback-panel-for-student.js
The old logic was preventing the text feedback or score from being shown if the rubric was hidden.
=> fix: Student report logic for when to show rubric [PT-188024567]

README.md, cypress/integration/feedback.spec.js, cypress/integration/portal-dashboard/portal-dashboard-activity-score.spec.js, cypress/integration/portal-dashboard/portal-dashboard-feedback.spec.js, js/components/authoring/rubric-test.js, js/components/portal-dashboard/feedback/rubric-utils.ts, js/core/rubric-migrations.js, public/sample-rubric.json, public/sample-v1-rubric.json, test/components/report/rubric-box_spec.js, test/core/rubric-migration_spec.js, test/util/rubric-helper_spec.js
Also added debug:rubricSummaryTableOverride query parameter to override the tag summary table rubric option.
=> feat: Updated sample rubric to v1.2 and added tag images and phrases [PT-188479846]

README.md, css/portal-dashboard/feedback/rubric-summary-modal.less, css/portal-dashboard/feedback/rubric-table.less, js/api.ts, js/components/portal-dashboard/feedback/rubric-summary-modal.tsx, js/components/portal-dashboard/feedback/rubric-table.tsx, js/core/rubric-migrations.js, js/util/debug-flags.js, js/util/debug-flags.ts, js/util/rubric-summary.ts, public/sample-rubric-all-dci-na.json, public/sample-rubric-no-tags.json, test/util/rubric-summary_spec.ts
Also:
1. Added debug:rubricUrlOverride parameter.
2. Added test rubrics.
3. Fixed non-version number change migration for iconPhrase.
**Sample branch urls for testing:**
- https://portal-report.concord.org/branch/add-tag-summary-table/?portal-dashboard=true&debug:rubricSummaryTableOverride=above
- https://portal-report.concord.org/branch/add-tag-summary-table/?portal-dashboard=true&debug:rubricSummaryTableOverride=below&debug:rubricUrlOverride=sample-rubric-no-tags.json
- https://portal-report.concord.org/branch/add-tag-summary-table/?portal-dashboard=true&debug:rubricSummaryTableOverride=onlySummary&debug:rubricUrlOverride=sample-rubric-all-dci-na.json
=> feat: Add rubric summary tag table [PT-188404153]

js/components/portal-dashboard/feedback/activity-level-feedback-student-rows.tsx, js/components/report/iframe-answer.tsx
The report item answers iframe was not loaded when the user navigated directly to the activity level feedback panel.  This caused the "Show Student Answers" dropdown to show a blank answer for any questions that had report items.
With this change all questions in the feedback panel that have report items pre-load all their report item iframes as hidden iframes before any of the student feedback rows are shown.  In addition a loading indicator was added while the report item answer is being loaded so that the answer does not look blank while the answer is loading.
=> fix: Report item answers not rendering in activity level feedback report [PT-188671164]

cypress/integration/api-error.spec.js, js/api.ts
When passed a url parameter without a scheme and the domain is localhost use http otherwise use https.
=> fix: Use http as fallback scheme for localhost

cypress/integration/portal-dashboard/portal-dashboard-activity-score.spec.js, cypress/integration/portal-dashboard/portal-dashboard-expand-activities.spec.js, cypress/integration/portal-dashboard/portal-dashboard-question-details.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-details.spec.js, cypress/integration/portal-dashboard/portal-dashboard-response-table.spec.js, cypress/integration/portal-dashboard/portal-dashboard-scrolling.spec.js, js/containers/portal-dashboard/portal-dashboard-app.tsx, js/selectors/dashboard-selectors.js
[CLASSDASH-69](https://concord-consortium.atlassian.net/browse/CLASSDASH-69)
If `currentActivity` is not set, we set it to be the first activity. This ensures the first activity is open by default.
Most of the files changed are Cypress test files that needed to be adjusted after the main change in `js/containers/portal-dashboard/portal-dashboard-app.tsx`.
[CLASSDASH-69]: https://concord-consortium.atlassian.net/browse/CLASSDASH-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: first activity is open by default (CLASSDASH-69)

cypress/integration/portal-dashboard/portal-dashboard-question-details.spec.js, js/components/portal-dashboard/overlay-class-response.tsx, js/components/portal-dashboard/question-overlay.tsx
[CLASSDASH-70](https://concord-consortium.atlassian.net/browse/CLASSDASH-70)
Changes the "Class Response" header text to "Class Summary". I decided to leave the class, variable, and component names the same (e.g., `classResponse`). That seemed to me to be a more apt description in the context of the code. I'm open to using "summary" in those things instead, though, if others think that'd be better?
[CLASSDASH-70]: https://concord-consortium.atlassian.net/browse/CLASSDASH-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: change Class Response header text (CLASSDASH-70)

cypress/integration/portal-dashboard/portal-dashboard-header.spec.js, js/components/portal-dashboard/header-menu-item.tsx, js/components/portal-dashboard/header-menu.tsx, js/components/portal-dashboard/header.tsx, js/containers/portal-dashboard/portal-dashboard-app.tsx
[CLASSDASH-67](https://concord-consortium.atlassian.net/browse/CLASSDASH-67)
This fixes an issue where the "Hide Last Run column" item in the header menu's selected state wasn't properly maintained across all views.
[CLASSDASH-67]: https://concord-consortium.atlassian.net/browse/CLASSDASH-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: base menu item selected state on props (CLASSDASH-67)

js/components/portal-dashboard/feedback/question-level-feedback-student-rows.tsx, js/containers/portal-dashboard/feedback/question-feedback-panel.tsx
[CLASSDASH-96](https://concord-consortium.atlassian.net/browse/CLASSDASH-96)
Adds the Last Run column to each student row in the question-level feedback view.
[CLASSDASH-96]: https://concord-consortium.atlassian.net/browse/CLASSDASH-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: last run timestamp missing on question-level feedback (CLASSDASH-96)
